#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.1
#  in conjunction with Tcl version 8.6
#    Oct 06, 2025 03:24:50 PM %z  platform: Windows NT

import sys
import ttkbootstrap as tk
from ttkbootstrap.constants import *
import os.path



_location = os.path.dirname(__file__)

import gui_support

_bgcolor = '#d9d9d9'
_fgcolor = '#000000'
_tabfg1 = 'black' 
_tabfg2 = 'white' 
_bgmode = 'light' 
_tabbg1 = '#d9d9d9' 
_tabbg2 = 'gray40' 

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        largeur_ecran,hauteur_ecran=gui_support.get_taill_ecran()
        top.geometry("1028x720")
        top.minsize(1540, 845)
        top.maxsize(largeur_ecran, hauteur_ecran)
        top.resizable(1,  1)
        top.title("Gestion d'inventaire")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="#000000")

        self.top = top
        self.choix_rapport=tk.StringVar(value="")
        #pour l'accueille
        self.Frame_home = tk.Frame(self.top)
        self.Frame_home.place(relx=0.164, rely=0.083, relheight=0.896, relwidth=0.831)
        
        self.Frame_graphe_pie = tk.Frame(self.Frame_home)
        self.Frame_graphe_pie.place(relx=0.565, rely=0.341, relheight=0.645
                , relwidth=0.417)


        self.Frame_grpahe_courbe = tk.Frame(self.Frame_home)
        self.Frame_grpahe_courbe.place(relx=0.023, rely=0.341, relheight=0.645
                , relwidth=0.522)

        self.Frame_total_budget = tk.Frame(self.Frame_home,bootstyle="info")
        self.Frame_total_budget.place(relx=0.029, rely=0.062, relheight=0.225
                , relwidth=0.309)
        self.icone_buged=gui_support.set_image_icone("icone/buged.png")
        self.Label_totalBudget = tk.Label(self.Frame_total_budget,image=self.icone_buged,compound="left",background="#3498DB")
        self.Label_totalBudget.place(relx=0.378, rely=0.069, height=32, relwidth=0.32)
        self.Label_totalBudget.configure(font="-family {Times New Roman} -size 12")
        self.Label_totalBudget.configure(text='''Total budget:''')

        self.Label_somme_budget = tk.Label(self.Frame_total_budget,background="#3498DB")
        self.Label_somme_budget.place(relx=0.031, rely=0.414, height=41
                , relwidth=0.94)
        self.Label_somme_budget.configure(font="-family {Times New Roman} -size 10")
        self.Label_somme_budget.configure(text='''0 Ar''')

        self.Frame_stock_critique = tk.Frame(self.Frame_home,bootstyle="warning")
        self.Frame_stock_critique.place(relx=0.368, rely=0.062, relheight=0.225
                , relwidth=0.282)
        self.Label_nombre_stock_critique = tk.Label(self.Frame_stock_critique,background="#F39C12")
        self.Label_nombre_stock_critique.place(relx=0.034, rely=0.414, height=41
                , relwidth=0.94)
        self.Label_nombre_stock_critique.configure(font="-family {Times New Roman} -size 10")
        self.Label_nombre_stock_critique.configure(text='''0 produit''')
        self.icone_happy=gui_support.set_image_icone('icone/happy.png')
        self.icone_sad=gui_support.set_image_icone('icone/sad.png')
        self.Label_stockCritique = tk.Label(self.Frame_stock_critique,compound="left",background="#F39C12")
        self.Label_stockCritique.place(relx=0.2, rely=0.062, height=32
                , width=250)
        self.Label_stockCritique.configure(font="-family {Times New Roman} -size 12")
        self.Label_stockCritique.configure(text='''Niveaux de stock critique:''')

        self.Frame_mouvement = tk.Frame(self.Frame_home,bootstyle="success")
        self.Frame_mouvement.place(relx=0.687, rely=0.062, relheight=0.225
                , relwidth=0.283)
        self.icone_mouvement=gui_support.set_image_icone('icone/mouv2.png')
        self.Label_mouvement = tk.Label(self.Frame_mouvement,image=self.icone_mouvement,compound="left",background="#00BC8C")
        self.Label_mouvement.place(relx=0.1, rely=0.069, height=32, width=320)
        self.Label_mouvement.configure(font="-family {Times New Roman} -size 12")
        self.Label_mouvement.configure(text=f'''Mouvement du stock: du {gui_support.get_date_now()}''') 

        self.Label_nombre_entre = tk.Label(self.Frame_mouvement,background="#00BC8C")
        self.Label_nombre_entre.place(relx=0.034, rely=0.345, height=31
                ,relwidth=0.94)
        self.Label_nombre_entre.configure(font="-family {Times New Roman} -size 10")
        self.Label_nombre_entre.configure(text=f"Entre : {gui_support.total_entre_sortie_today()[0]} produit(s)")

        self.Label_nombre_sortie = tk.Label(self.Frame_mouvement,background="#00BC8C")
        self.Label_nombre_sortie.place(relx=0.034, rely=0.69, height=31
                , relwidth=0.94)
        self.Label_nombre_sortie.configure(font="-family {Times New Roman} -size 10")
        self.Label_nombre_sortie.configure(text=f"Sortie : {gui_support.total_entre_sortie_today()[1]} produit(s)")

        self.Frame_menu_principale = tk.Frame(self.top)
        self.Frame_menu_principale.place(relx=0.007, rely=0.088, relheight=0.896
                , relwidth=0.145)
        #on cree notre menu tree
        self.menu=tk.Treeview(self.Frame_menu_principale,bootstyle="success")
        self.menu.pack(fill="both",expand=True)
        #on creer nos menus et sous-menu
        #menu accueill
        #des icones
        self.icone_add=gui_support.set_image_icone("icone/Add.png")
        self.icone_modify=gui_support.set_image_icone("icone/mouv.png")
        self.icone_delete=gui_support.set_image_icone("icone/supprimer.png")
        self.icone_rapport=gui_support.set_image_icone("icone/rapport.png")
        self.icone_fournisseur=gui_support.set_image_icone("icone/fournisseur.png")
        self.icone_inventaire=gui_support.set_image_icone("icone/inventaire.png")
        self.icone_home=gui_support.set_image_icone("icone/maison.png")
        menu_accueil=self.menu.insert("","end",text="Accueil",image=self.icone_home)
        #menu inventaire
        menu_inventaire=self.menu.insert("","end",text="Inventaire",open=True,image=self.icone_inventaire)
        #ses sous menu
        self.menu.insert(menu_inventaire,'end',text="Ajouter un produit",image=self.icone_add)
        self.menu.insert(menu_inventaire,'end',text="Modifier un produit",image=self.icone_modify)
        self.menu.insert(menu_inventaire,'end',text="Suprimer un produit",image=self.icone_delete)
        #menu fournisseur
        menu_fournisseur=self.menu.insert("","end",text="Fournisseur",open=True,image=self.icone_fournisseur)
        #ses sous menu
        self.menu.insert(menu_fournisseur,"end",text="Ajouter un fournisseur",image=self.icone_add)
        self.menu.insert(menu_fournisseur,"end",text="Modifier un fournisseur",image=self.icone_modify)
        self.menu.insert(menu_fournisseur,"end",text="Suprimer un fournisseur",image=self.icone_delete)
        #menu Rapport
        menu_rapport=self.menu.insert("","end",text="Rapport",open=True,image=self.icone_rapport)
        #ses sous menu
        self.menu.insert(menu_rapport,"end",text="Journalier")
        self.menu.insert(menu_rapport,"end",text="Mensuelle")
        self.menu.insert(menu_rapport,"end",text="Trimestre")
        self.menu.insert(menu_rapport,"end",text="Semestre")
        self.menu.insert(menu_rapport,"end",text="Annuelle")

        self.TSeparator1 = tk.Separator(self.Frame_menu_principale)
        self.TSeparator1.place(relx=-0.108, rely=0.803,  relwidth=1.161)

        self.Button_quitter = tk.Button(self.Frame_menu_principale,bootstyle="outline-danger")
        self.Button_quitter.place(relx=0.113, rely=0.898, height=36, relwidth=0.75)
        self.Button_quitter.configure(text='''Quitter''')

        self.Frame_menu_bare = tk.Frame(self.top)
        self.Frame_menu_bare.place(relx=0.0, rely=0.0, relheight=0.069
                , relwidth=1.004)
        ####################################################
        #pour le rechercher produit
        self.Frame_find_produit = tk.Frame(self.Frame_menu_bare)
        self.Frame_find_produit.place(relx=0.514, rely=0.0, relheight=1.02
                , relwidth=0.486)

        self.Entry_find_produit = tk.Entry(self.Frame_find_produit,bootstyle="info")
        self.Entry_find_produit.place(relx=0.21, rely=0.2, height=33
                , relwidth=0.646)
        self.icone_actu=gui_support.set_image_icone('icone/actu.png')
        self.Label_find_produit = tk.Label(self.Frame_find_produit,image=self.icone_actu)
        self.Label_find_produit.place(relx=0.896, rely=0.2, height=31, width=44)

        self.Label1 = tk.Label(self.Frame_find_produit)
        self.Label1.place(relx=0.1, rely=0.2, height=21, relwidth=0.1)
        self.Label1.configure(text='''Recherche :''')
        ####################################################
        #pour masque le zone de recherche produit et fournisseur
        self.Frame_find_vide = tk.Frame(self.Frame_menu_bare)
        self.Frame_find_vide.place(relx=0.514, rely=0.0, relheight=1.02
                , relwidth=0.486)
        ####################################################
        #pour le rechercher fournisseur
        self.Frame_find_fournisseur = tk.Frame(self.Frame_menu_bare)
        self.Frame_find_fournisseur.place(relx=0.514, rely=0.0, relheight=1.02
                , relwidth=0.486)

        self.Entry_find_fournisseur = tk.Entry(self.Frame_find_fournisseur,bootstyle="info")
        self.Entry_find_fournisseur.place(relx=0.21, rely=0.2, height=33
                , relwidth=0.646)
        self.Label_find_fournisseur = tk.Label(self.Frame_find_fournisseur,image=self.icone_actu)
        self.Label_find_fournisseur.place(relx=0.896, rely=0.2, height=31, width=44)

        self.Label1 = tk.Label(self.Frame_find_fournisseur)
        self.Label1.place(relx=0.1, rely=0.2, height=21, relwidth=0.1)
        self.Label1.configure(text='''Recherche :''')
        #############################################################
        #un frame vide pour masque les flitre produits
        self.Frame_none = tk.Frame(self.Frame_menu_bare)
        self.Frame_none.place(relx=0.0, rely=0.0, relheight=1.0
                , relwidth=0.437)
        ##############################################################
        #pour faire une filtre sur le produit pour le rapport:
        self.Frame_filtrer_produit_rapport = tk.Frame(self.Frame_menu_bare)
        self.Frame_filtrer_produit_rapport.place(relx=0.0, rely=0.0, relheight=1.0
                , relwidth=0.437)
        
        liste_filtre=["Tous","Électronique","Fourniture","PPN","Textille","Accésoire","Boisson"]# la liste de categorie

        self.Label1 = tk.Label(self.Frame_filtrer_produit_rapport)
        self.Label1.place(relx=0.022, rely=0.22, height=23, width=70)
        self.Label1.configure(text='''Produit:''')

        self.Combobox_categorie_filtre_rapport = tk.Combobox(self.Frame_filtrer_produit_rapport,values=liste_filtre)
        self.Combobox_categorie_filtre_rapport.place(relx=0.141, rely=0.14
                , relheight=0.66, relwidth=0.4)
        self.Combobox_categorie_filtre_rapport.current(0)
        ##############################################################
        #pour faire une filtre sur le produit
        self.Frame_filtrer_produit = tk.Frame(self.Frame_menu_bare)
        self.Frame_filtrer_produit.place(relx=0.0, rely=0.0, relheight=1.0
                , relwidth=0.437)

        self.Label1 = tk.Label(self.Frame_filtrer_produit)
        self.Label1.place(relx=0.022, rely=0.22, height=23, width=70)
        self.Label1.configure(text='''Produit:''')

        self.Combobox_categorie_filtre = tk.Combobox(self.Frame_filtrer_produit,values=liste_filtre)
        self.Combobox_categorie_filtre.place(relx=0.141, rely=0.14
                , relheight=0.66, relwidth=0.4)
        
        self.Combobox_categorie_filtre.current(0)
        
        self.Button_filtrer = tk.Button(self.Frame_filtrer_produit,bootstyle="outline-info")
        self.Button_filtrer.place(relx=0.6, rely=0.20, height=30, relwidth=0.15)
        self.Button_filtrer.configure(text='''Filtre''')

        #on ajoute un icone d'exportation
        self.icone_exportation=gui_support.set_image_icone("icone/exporter.png")
        self.Button_exporter_produit = tk.Label(self.Frame_filtrer_produit,image=self.icone_exportation)
        self.Button_exporter_produit.place(relx=0.8, rely=0.20, height=30
                ,relwidth=0.15)
        #########################################################
        #pour exporter les fournisseur
        self.Frame_expo_fournisseur = tk.Frame(self.Frame_menu_bare)
        self.Frame_expo_fournisseur.place(relx=0.0, rely=0.0, relheight=1.0
                , relwidth=0.437)
        
        self.Button_exportation_fournisseur = tk.Label(self.Frame_expo_fournisseur,image=self.icone_exportation)
        self.Button_exportation_fournisseur.place(relx=0.022, rely=0.22, height=23, width=70)
        #########################################################
        #intervace home inventaire
        self.Frame_Inventaire = tk.Frame(self.top)
        self.Frame_Inventaire.place(relx=0.164, rely=0.083, relheight=0.896, relwidth=0.831)
        #pour le tableaux d'inventaire
        #les colonner
        colonne=["Produit","Catégorie","Quantite","Prix","Fournisseur","Date (annee-mois-jour)"]
        self.table_inventaire_home = tk.Treeview(self.Frame_Inventaire,columns=colonne,show="headings",bootstyle="info")
        #on ajoute un scroll bar
        self.scroll_table_inventaire_home=tk.Scrollbar(self.table_inventaire_home,orient="vertical",bootstyle="info")
        self.scroll_table_inventaire_home.place(relx=0.980,rely=0.050,width=30,relheight=0.930)
        self.table_inventaire_home.configure(yscrollcommand=self.scroll_table_inventaire_home.set)
       
        self.table_inventaire_home.place(relx=0.013, rely=0.031, relheight=0.935
                , relwidth=0.977)
        #on cofigure le table d'inventaire

        self.scroll_table_inventaire_home.configure(command=self.table_inventaire_home.yview)

        for col in colonne:
           self.table_inventaire_home.heading(col,text=col)
           self.table_inventaire_home.column(col,width=50,anchor="center")
        #Pour interface ajouter produit
        self.Frame_Inventaire_ajouter = tk.Frame(self.top)
        self.Frame_Inventaire_ajouter.place(relx=0.164, rely=0.083
                , relheight=0.896, relwidth=0.831)
        
        self.Label_categorie_produit = tk.Label(self.Frame_Inventaire_ajouter)
        self.Label_categorie_produit.place(relx=0.01, rely=0.729, height=31
                , width=86)
        self.Label_categorie_produit.configure(text='''Catégorie :''')

        self.Label_nom_produit = tk.Label(self.Frame_Inventaire_ajouter)
        self.Label_nom_produit.place(relx=0.029, rely=0.667, height=22, width=55)
        self.Label_nom_produit.configure(text='''Nom :''')

        self.Combobox_categorie_produit = tk.Combobox(self.Frame_Inventaire_ajouter)
        self.Combobox_categorie_produit.place(relx=0.087, rely=0.729, relheight=0.05, relwidth=0.374)

        self.Label_quantite_produit = tk.Label(self.Frame_Inventaire_ajouter)
        self.Label_quantite_produit.place(relx=0.01, rely=0.806, height=31
                , width=76)
        self.Label_quantite_produit.configure(text='''Quantite :''')

        self.Spinbox_quantite_produit = tk.Spinbox(self.Frame_Inventaire_ajouter, from_=1, to=1000000000)
        self.Spinbox_quantite_produit.place(relx=0.087, rely=0.806
                , relheight=0.05, relwidth=0.374)

        self.Label_prix_produit = tk.Label(self.Frame_Inventaire_ajouter)
        self.Label_prix_produit.place(relx=0.01, rely=0.884, height=31, width=54)
        self.Label_prix_produit.configure(text='''Prix :''')

        self.Entry_nom_produit = tk.Entry(self.Frame_Inventaire_ajouter)
        self.Entry_nom_produit.place(relx=0.087, rely=0.651, height=32
                , relwidth=0.37)
        
        self.Spinbox_prix_produit = tk.Spinbox(self.Frame_Inventaire_ajouter, from_=1.0, to=100.0)
        self.Spinbox_prix_produit.place(relx=0.087, rely=0.884, relheight=0.05
                , relwidth=0.374)

        self.Label_fournisseur_produit = tk.Label(self.Frame_Inventaire_ajouter)
        self.Label_fournisseur_produit.place(relx=0.564, rely=0.682, height=31
                , width=94)
        self.Label_fournisseur_produit.configure(text='''Fournisseur :''')

        self.Combobox_fournisseur_produit = tk.Combobox(self.Frame_Inventaire_ajouter)
        self.Combobox_fournisseur_produit.place(relx=0.648, rely=0.682
                , relheight=0.05, relwidth=0.336)
        self.Combobox_fournisseur_produit.configure(values=gui_support.recuperer_fournisseur())
        self.Combobox_fournisseur_produit.current(0)

        self.Button_ajouter_produit = tk.Button(self.Frame_Inventaire_ajouter,bootstyle="success")
        self.Button_ajouter_produit.place(relx=0.564, rely=0.837, height=36
                , width=177)
        self.Button_ajouter_produit.configure(text='''Ajouter''')
        #pour le tableaux d'inventaire
        #les colonner
        self.table_inventaire = tk.Treeview(self.Frame_Inventaire_ajouter,columns=colonne,show="headings",bootstyle="info")
        self.table_inventaire.place(relx=0.013, rely=0.031, relheight=0.612
                , relwidth=0.977)
        #on creer un scrobar
        self.scroll_table_inventaire=tk.Scrollbar(self.table_inventaire,orient="vertical",bootstyle="info")
        self.scroll_table_inventaire.place(relx=0.980, rely=0.080, relheight=0.9 ,width=30)
        self.table_inventaire.configure(yscrollcommand=self.scroll_table_inventaire.set)
        self.scroll_table_inventaire.configure(command=self.table_inventaire.yview)
        #on cofigure le table d'inventaire
        for col in colonne:
           self.table_inventaire.heading(col,text=col)
           self.table_inventaire.column(col,width=50,anchor="center")

        self.Button_suprimer_produit = tk.Button(self.Frame_Inventaire_ajouter,bootstyle="danger")
        self.Button_suprimer_produit.place(relx=0.808, rely=0.837, height=36
                , width=167)
        self.Button_suprimer_produit.configure(text='''Suprimer''')

        #Pour l'interface inventaire produit modifier
        self.Frame_Inventaire_modifier = tk.Frame(self.top)
        self.Frame_Inventaire_modifier.place(relx=0.164, rely=0.083
                , relheight=0.896, relwidth=0.831)

        self.Combobox_categorie_produit_modifier = tk.Combobox(self.Frame_Inventaire_modifier)
        self.Combobox_categorie_produit_modifier.place(relx=0.087, rely=0.729
                , relheight=0.05, relwidth=0.374)
        
        self.Spinbox_quantite_produit_modifier = tk.Spinbox(self.Frame_Inventaire_modifier, from_=1, to=1000000000)
        self.Spinbox_quantite_produit_modifier.place(relx=0.087, rely=0.806
                , relheight=0.05, relwidth=0.374)

        self.Entry_nom_produit_modifier = tk.Entry(self.Frame_Inventaire_modifier)
        self.Entry_nom_produit_modifier.place(relx=0.087, rely=0.651, height=32
                , relwidth=0.37)

        self.Spinbox_prix_produit_modifier = tk.Spinbox(self.Frame_Inventaire_modifier, from_=1, to=1000000000)
        self.Spinbox_prix_produit_modifier.place(relx=0.087, rely=0.884, relheight=0.05
                , relwidth=0.374)

        self.Label_nom_produit_modifier = tk.Label(self.Frame_Inventaire_modifier)
        self.Label_nom_produit_modifier.place(relx=0.029, rely=0.667, height=22
                , width=55)
        self.Label_nom_produit_modifier.configure(text='''Nom :''')

        self.Label_categorie_produit_modifier = tk.Label(self.Frame_Inventaire_modifier)
        self.Label_categorie_produit_modifier.place(relx=0.01, rely=0.729
                , height=31, width=86)
        self.Label_categorie_produit_modifier.configure(text='''Catégorie :''')

        self.Label_quantite_produit_modifier = tk.Label(self.Frame_Inventaire_modifier)
        self.Label_quantite_produit_modifier.place(relx=0.01, rely=0.806
                , height=31, width=76)
        self.Label_quantite_produit_modifier.configure(text='''Quantite :''')

        self.Label_prix_produit_modifier = tk.Label(self.Frame_Inventaire_modifier)
        self.Label_prix_produit_modifier.place(relx=0.01, rely=0.884, height=31
                , width=54)
        self.Label_prix_produit_modifier.configure(text='''Prix :''')

        self.Label_fournisseur_produit_modifier = tk.Label(self.Frame_Inventaire_modifier)
        self.Label_fournisseur_produit_modifier.place(relx=0.564, rely=0.682
                , height=31, width=94)
        self.Label_fournisseur_produit_modifier.configure(text='''Fournisseur :''')

        self.Label_mouvement_stock = tk.Label(self.Frame_Inventaire_modifier)
        self.Label_mouvement_stock.place(relx=0.564, rely=0.76, height=31
                , width=94)
        self.Label_mouvement_stock.configure(text='''Mouvement :''')

        self.Combobox_fournisseur_produit_modifier = tk.Combobox(self.Frame_Inventaire_modifier)
        self.Combobox_fournisseur_produit_modifier.place(relx=0.648, rely=0.682
                , relheight=0.05, relwidth=0.336)
        self.Combobox_fournisseur_produit_modifier.config(values=self.Combobox_fournisseur_produit['values'])
        

        self.Button_modifier_produit = tk.Button(self.Frame_Inventaire_modifier,bootstyle="info")
        self.Button_modifier_produit.place(relx=0.724, rely=0.93, height=36
                , width=177)
        self.Button_modifier_produit.configure(text='''Modifier''')
        #pour le tableux d'inventaire a modifier
        self.table_inventaire_modifier = tk.Treeview(self.Frame_Inventaire_modifier,columns=colonne,show="headings",bootstyle="info")
        self.table_inventaire_modifier.place(relx=0.013, rely=0.031
                , relheight=0.612, relwidth=0.977)
         #on creer un scrobar
        self.scroll_table_inventaire_modifier=tk.Scrollbar(self.table_inventaire_modifier,orient="vertical",bootstyle="info")
        self.scroll_table_inventaire_modifier.place(relx=0.980, rely=0.080, relheight=0.9 ,width=30)
        self.table_inventaire_modifier.configure(yscrollcommand=self.scroll_table_inventaire.set)
        self.scroll_table_inventaire_modifier.configure(command=self.table_inventaire_modifier.yview)
        #on configure le tableau
        for cols in colonne:
            self.table_inventaire_modifier.heading(cols,text=cols)
            self.table_inventaire_modifier.column(cols,width=50,anchor="center")

        self.Combobox_mouvement = tk.Combobox(self.Frame_Inventaire_modifier)
        self.Combobox_mouvement.place(relx=0.648, rely=0.76, relheight=0.05
                , relwidth=0.336)
        self.value_list = ['Aucun','Entre','Sortie',]
        self.Combobox_mouvement.configure(values=self.value_list)
        self.Combobox_mouvement.current(0)

        self.Spinbox_stock_mouvement = tk.Spinbox(self.Frame_Inventaire_modifier, from_=1, to=1000000000)
        self.Spinbox_stock_mouvement.place(relx=0.648, rely=0.837, relheight=0.05
                , relwidth=0.336)

        self.Label_stock_mouvement = tk.Label(self.Frame_Inventaire_modifier)
        self.Label_stock_mouvement.place(relx=0.573, rely=0.837, height=21
                , width=54)
        self.Label_stock_mouvement.configure(text='''Stock :''')
        #pour l'interface home fournisseur
        self.Frame_fournisseur_home = tk.Frame(self.top)
        self.Frame_fournisseur_home.place(relx=0.164, rely=0.083, relheight=0.896
                , relwidth=0.831)
        #pour le tableau de fournisseur
        colonne_fournisseur=["Nom","Adresse","Télèphone","E-mail","Date (annee-mois-jour)"]
        self.table_fournisseur_home = tk.Treeview(self.Frame_fournisseur_home,columns=colonne_fournisseur,show="headings",bootstyle="info")
        self.table_fournisseur_home.place(relx=0.013, rely=0.031, relheight=0.935
                , relwidth=0.977)
        #on creer un scrobar
        self.scroll_table_f1=tk.Scrollbar(self.table_fournisseur_home,orient="vertical",bootstyle="info")
        self.scroll_table_f1.place(relx=0.980,rely=0.050,width=30,relheight=0.930)
        self.table_fournisseur_home.configure(yscrollcommand=self.scroll_table_f1.set)
        self.scroll_table_f1.configure(command=self.table_fournisseur_home.yview)
        #on configure le tableau
        for col in colonne_fournisseur:
            self.table_fournisseur_home.heading(col,text=col)
            self.table_fournisseur_home.column(col,width=50,anchor="center")
        #Pour l'interface Fournisseur
        self.Frame_fournisseur = tk.Frame(self.top)
        self.Frame_fournisseur.place(relx=0.164, rely=0.083, relheight=0.896
                , relwidth=0.831)

        self.Label_nom_produit = tk.Label(self.Frame_fournisseur)
        self.Label_nom_produit.place(relx=0.029, rely=0.667, height=22, width=55)
        self.Label_nom_produit.configure(text='''Nom :''')

        self.Entry_nom_fournisseur = tk.Entry(self.Frame_fournisseur)
        self.Entry_nom_fournisseur.place(relx=0.087, rely=0.651, height=32
                , relwidth=0.37)

        self.Label_telephone = tk.Label(self.Frame_fournisseur)
        self.Label_telephone.place(relx=0.01, rely=0.806, height=31, width=76)
        self.Label_telephone.configure(text='''Télèphone :''')

        self.Label_email = tk.Label(self.Frame_fournisseur)
        self.Label_email.place(relx=0.01, rely=0.884, height=31, width=54)
        self.Label_email.configure(text='''E-mail :''')

        self.Entry_telephone = tk.Entry(self.Frame_fournisseur)
        self.Entry_telephone.place(relx=0.085, rely=0.806, height=32
                , relwidth=0.37)

        self.Entry_email = tk.Entry(self.Frame_fournisseur)
        self.Entry_email.place(relx=0.087, rely=0.884, height=32, relwidth=0.37)
        #pour le tableau de fournisseur
        self.table_fournisseur = tk.Treeview(self.Frame_fournisseur,columns=colonne_fournisseur,show="headings",bootstyle="info")
        self.table_fournisseur.place(relx=0.013, rely=0.031, relheight=0.612
                , relwidth=0.977)
         #on creer un scrobar
        self.scroll_table_f2=tk.Scrollbar(self.table_fournisseur,orient="vertical",bootstyle="info")
        self.scroll_table_f2.place(relx=0.980, rely=0.080, relheight=0.9 ,width=30)
        self.table_fournisseur.configure(yscrollcommand=self.scroll_table_f2.set)
        self.scroll_table_f2.configure(command=self.table_fournisseur.yview)
        #on configure le tableau
        for col in colonne_fournisseur:
            self.table_fournisseur.heading(col,text=col)
            self.table_fournisseur.column(col,width=50,anchor="center")

        self.Label_adresse_fournisseur = tk.Label(self.Frame_fournisseur)
        self.Label_adresse_fournisseur.place(relx=0.01, rely=0.729, height=31
                , width=86)
        self.Label_adresse_fournisseur.configure(text='''Adresse :''')

        self.Button_ajouter_fournisseur = tk.Button(self.Frame_fournisseur,bootstyle="success")
        self.Button_ajouter_fournisseur.place(relx=0.695, rely=0.667, height=36
                , width=177)
        self.Button_ajouter_fournisseur.configure(text='''Ajouter''')

        self.Button_modifier_fournisseur = tk.Button(self.Frame_fournisseur,bootstyle="info")
        self.Button_modifier_fournisseur.place(relx=0.695, rely=0.775, height=36
                , width=177)
        self.Button_modifier_fournisseur.configure(text='''Modifier''')

        self.Button_suprimer_fournisseur = tk.Button(self.Frame_fournisseur,bootstyle="danger")
        self.Button_suprimer_fournisseur.place(relx=0.695, rely=0.899, height=36
                , width=177)
        self.Button_suprimer_fournisseur.configure(text='''Suprimer''')

        self.Entry_adresse = tk.Entry(self.Frame_fournisseur)
        self.Entry_adresse.place(relx=0.087, rely=0.729, height=32
                , relwidth=0.37)
        #######################################################################
        #pour l'interface rapport journalier
        self.Frame_rapport = tk.Frame(self.top)
        self.Frame_rapport.place(relx=0.164, rely=0.083, relheight=0.896
                , relwidth=0.831)
        #on configure la tableaux rapport:
        colonnes_rapport=["Produit","Stock initiale","Entre","Sortie","Stock final","Commentaire"]
        self.table_rapport = tk.Treeview(self.Frame_rapport,show="headings",columns=colonnes_rapport,bootstyle="info")
        self.table_rapport.place(relx=0.301, rely=0.031, relheight=0.953, relwidth=0.683)
         #on creer un scrobar
        self.scroll_table=tk.Scrollbar(self.table_rapport,orient="vertical",bootstyle="info")
        self.scroll_table.place(relx=0.975, rely=0.080, relheight=0.9 ,width=30)
        self.table_rapport.configure(yscrollcommand=self.scroll_table.set)
        self.scroll_table.configure(command=self.table_rapport.yview)
        #on ajouter les entête du tableau
        for col in colonnes_rapport:
            self.table_rapport.heading(col,text=col)
            self.table_rapport.column(col,width=50,anchor="center")

        self.Frame_option_jounalier = tk.Frame(self.Frame_rapport)
        self.Frame_option_jounalier.place(relx=0.009, rely=0.031, relheight=0.953
                , relwidth=0.273)

        self.Label_journalier = tk.Label(self.Frame_option_jounalier)
        self.Label_journalier.place(relx=0.247, rely=0.016, height=31, width=170)
        self.Label_journalier.configure(text='''RAPPORT: JOURNALIER''')

        self.Radio_jour_now = tk.Radiobutton(self.Frame_option_jounalier,variable=self.choix_rapport,value="jour_now")
        self.Radio_jour_now.place(relx=0.107, rely=0.13, relheight=0.057
                , relwidth=0.454)
        self.Radio_jour_now.configure(text='''Aujourd'hui''')

        self.Radio_jour_specique = tk.Radiobutton(self.Frame_option_jounalier,variable=self.choix_rapport,value="jour_specifique")
        self.Radio_jour_specique.place(relx=0.107, rely=0.341, relheight=0.057
                , relwidth=0.75)
        self.Radio_jour_specique.configure(text='''Date spécifique (annee-mois-jour)''')


        self.Label1 = tk.Label(self.Frame_option_jounalier)
        self.Label1.place(relx=0.072, rely=0.455, height=31, width=55)
        self.Label1.configure(text='''Date :''')

        self.Date_jour_specique = tk.DateEntry(self.Frame_option_jounalier,dateformat="%Y-%m-%d")
        self.Date_jour_specique.place(relx=0.251, rely=0.455, height=32
                , relwidth=0.701)

        self.TSeparator2 = tk.Separator(self.Frame_option_jounalier)
        self.TSeparator2.place(relx=0.034, rely=0.26,  relwidth=0.928)

        self.TSeparator3 = tk.Separator(self.Frame_option_jounalier)
        self.TSeparator3.place(relx=0.055, rely=0.623,  relwidth=0.9)

        self.Button_generer_journalier = tk.Button(self.Frame_option_jounalier,bootstyle="outline-success")
        self.Button_generer_journalier.place(relx=0.137, rely=0.732, height=46
                , relwidth=0.75)
        self.Button_generer_journalier.configure(text='''Générer''')

        self.Button_exportation_journalier = tk.Button(self.Frame_option_jounalier,bootstyle="outline-info")
        self.Button_exportation_journalier.place(relx=0.137, rely=0.894, height=46
                , relwidth=0.75)
        self.Button_exportation_journalier.configure(text='''Exporter''')
        #######################################################################
        #pour l'interface rapport mensuelle

        self.Frame_option_mensuelle = tk.Frame(self.Frame_rapport)
        self.Frame_option_mensuelle.place(relx=0.009, rely=0.031, relheight=0.953
                , relwidth=0.273)

        self.Label_mensuelle = tk.Label(self.Frame_option_mensuelle)
        self.Label_mensuelle.place(relx=0.247, rely=0.016, height=31, width=170)
        self.Label_mensuelle.configure(text='''RAPPORT: MENSUELLE''')

        self.Label1 = tk.Label(self.Frame_option_mensuelle)
        self.Label1.place(relx=0.072, rely=0.455, height=31, width=55)
        self.Label1.configure(text='''Mois :''')

        self.mois_specique = tk.Combobox(self.Frame_option_mensuelle,bootstyle="danger")
        self.mois_specique.place(relx=0.251, rely=0.455, height=32
                , relwidth=0.701)
        mois_liste=["Janvier","Février","Mars","Avril","Mai","Juin","Juillet","Août","Septembre","Octobre","Novembre","Décembre"]
        self.mois_specique.configure(values=mois_liste)
        self.mois_specique.current(0)

        self.Label2 = tk.Label(self.Frame_option_mensuelle)
        self.Label2.place(relx=0.072, rely=0.555, height=31, width=55)
        self.Label2.configure(text='''Année :''')

        self.moisETannee_specique = tk.Combobox(self.Frame_option_mensuelle,bootstyle="danger")
        self.moisETannee_specique.place(relx=0.251, rely=0.555, height=32
                , relwidth=0.701)
        annee_liste=[]
        for annee in range(2025,2061):
            annee_liste.append(annee)
        
        self.moisETannee_specique.configure(values=annee_liste)
        self.moisETannee_specique.current(0)

        self.TSeparator2 = tk.Separator(self.Frame_option_mensuelle)
        self.TSeparator2.place(relx=0.034, rely=0.26,  relwidth=0.928)

        self.TSeparator3 = tk.Separator(self.Frame_option_mensuelle)
        self.TSeparator3.place(relx=0.055, rely=0.623,  relwidth=0.9)

        self.Button_generer_mensuelle = tk.Button(self.Frame_option_mensuelle,bootstyle="outline-success")
        self.Button_generer_mensuelle.place(relx=0.137, rely=0.732, height=46
                , relwidth=0.75)
        self.Button_generer_mensuelle.configure(text='''Générer''')

        self.Button_exportation_mensuelle = tk.Button(self.Frame_option_mensuelle,bootstyle="outline-info")
        self.Button_exportation_mensuelle.place(relx=0.137, rely=0.894, height=46
                , relwidth=0.75)
        self.Button_exportation_mensuelle.configure(text='''Exporter''')
        #######################################################################
        #pour l'interface rapport Annuelle

        self.Frame_option_annuelle = tk.Frame(self.Frame_rapport)
        self.Frame_option_annuelle.place(relx=0.009, rely=0.031, relheight=0.953
                , relwidth=0.273)

        self.Label_annuelle = tk.Label(self.Frame_option_annuelle)
        self.Label_annuelle.place(relx=0.247, rely=0.016, height=31, width=170)
        self.Label_annuelle.configure(text='''RAPPORT: ANNUELLE''')

        self.Label1 = tk.Label(self.Frame_option_annuelle)
        self.Label1.place(relx=0.072, rely=0.455, height=31, width=55)
        self.Label1.configure(text='''Année :''')

        self.annee_specique = tk.Combobox(self.Frame_option_annuelle,bootstyle="danger")
        self.annee_specique.place(relx=0.251, rely=0.455, height=32
                , relwidth=0.701)
        
        self.annee_specique.configure(values=annee_liste)
        self.annee_specique.current(0)

        self.TSeparator2 = tk.Separator(self.Frame_option_annuelle)
        self.TSeparator2.place(relx=0.034, rely=0.26,  relwidth=0.928)

        self.TSeparator3 = tk.Separator(self.Frame_option_annuelle)
        self.TSeparator3.place(relx=0.055, rely=0.623,  relwidth=0.9)

        self.Button_generer_annuelle = tk.Button(self.Frame_option_annuelle,bootstyle="outline-success")
        self.Button_generer_annuelle.place(relx=0.137, rely=0.732, height=46
                , relwidth=0.75)
        self.Button_generer_annuelle.configure(text='''Générer''')

        self.Button_exportation_annuelle = tk.Button(self.Frame_option_annuelle,bootstyle="outline-info")
        self.Button_exportation_annuelle.place(relx=0.137, rely=0.894, height=46
                , relwidth=0.75)
        self.Button_exportation_annuelle.configure(text='''Exporter''')
        #######################################################################
        #pour l'interface rapport Trimestre

        self.Frame_option_trimestre = tk.Frame(self.Frame_rapport)
        self.Frame_option_trimestre.place(relx=0.009, rely=0.031, relheight=0.953
                , relwidth=0.273)

        self.Label_trimestre = tk.Label(self.Frame_option_trimestre)
        self.Label_trimestre.place(relx=0.247, rely=0.016, height=31, width=170)
        self.Label_trimestre.configure(text='''RAPPORT: TRIMESTRIEL''')
        colonne_trimestre=["T1","T2","T3","T4"]
        self.table_trimestre = tk.Treeview(self.Frame_option_trimestre,show="headings",columns=colonne_trimestre,bootstyle="success")
        self.table_trimestre.place(relx=0.02,rely=0.055,relwidth=0.95,relheight=0.2)
        #on cofigure le tableaux
        for cols in colonne_trimestre:
            self.table_trimestre.heading(cols,text=cols)
            self.table_trimestre.column(cols,width=30)
        #on ajoute les ligne du tableau
        liste_trimestre=["Janvier-Mars","Avril-Juin","Juillet-Septembre","Octobre-Décembre"]
        self.table_trimestre.insert("","end",values=liste_trimestre)

        self.Label1 = tk.Label(self.Frame_option_trimestre)
        self.Label1.place(relx=0.072, rely=0.455, height=31, width=55)
        self.Label1.configure(text='''Année :''')

        self.trim_annee_specique = tk.Combobox(self.Frame_option_trimestre,bootstyle="danger")
        self.trim_annee_specique.place(relx=0.251, rely=0.455, height=32
                , relwidth=0.701)
        
        self.trim_annee_specique.configure(values=annee_liste)
        self.trim_annee_specique.current(0)
        
        self.Label2 = tk.Label(self.Frame_option_trimestre)
        self.Label2.place(relx=0.072, rely=0.555, height=31, width=50)
        self.Label2.configure(text='''Trim :''')

        self.trim_combox = tk.Combobox(self.Frame_option_trimestre,bootstyle="danger")
        self.trim_combox.place(relx=0.251, rely=0.555, height=32
                , relwidth=0.701)
        
        self.trim_combox.configure(values=colonne_trimestre)
        self.trim_combox.current(0)

        self.TSeparator2 = tk.Separator(self.Frame_option_trimestre)
        self.TSeparator2.place(relx=0.034, rely=0.26,  relwidth=0.928)

        self.TSeparator3 = tk.Separator(self.Frame_option_trimestre)
        self.TSeparator3.place(relx=0.055, rely=0.623,  relwidth=0.9)

        self.Button_generer_trimestre = tk.Button(self.Frame_option_trimestre,bootstyle="outline-success")
        self.Button_generer_trimestre.place(relx=0.137, rely=0.732, height=46
                , relwidth=0.75)
        self.Button_generer_trimestre.configure(text='''Générer''')

        self.Button_exportation_trimestre = tk.Button(self.Frame_option_trimestre,bootstyle="outline-info")
        self.Button_exportation_trimestre.place(relx=0.137, rely=0.894, height=46
                , relwidth=0.75)
        self.Button_exportation_trimestre.configure(text='''Exporter''')
        #######################################################################
        #pour l'interface rapport Semestre

        self.Frame_option_semestre = tk.Frame(self.Frame_rapport)
        self.Frame_option_semestre.place(relx=0.009, rely=0.031, relheight=0.953
                , relwidth=0.273)

        self.Label_semestre = tk.Label(self.Frame_option_semestre)
        self.Label_semestre.place(relx=0.247, rely=0.016, height=31, width=170)
        self.Label_semestre.configure(text='''RAPPORT: SEMESTRIEL''')
        colonne_semestre=["S1","S2"]
        self.table_semestre = tk.Treeview(self.Frame_option_semestre,show="headings",columns=colonne_semestre,bootstyle="success")
        self.table_semestre.place(relx=0.02,rely=0.055,relwidth=0.95,relheight=0.2)
        #on cofigure le tableaux
        for cols in colonne_semestre:
            self.table_semestre.heading(cols,text=cols)
            self.table_semestre.column(cols,width=30)
        #on ajoute les ligne du tableau
        liste_semestre=["Janvier-Juin","Juillet-Décembre"]
        self.table_semestre.insert("","end",values=liste_semestre)

        self.Label1 = tk.Label(self.Frame_option_semestre)
        self.Label1.place(relx=0.072, rely=0.455, height=31, width=55)
        self.Label1.configure(text='''Année :''')

        self.sem_annee_specique = tk.Combobox(self.Frame_option_semestre,bootstyle="danger")
        self.sem_annee_specique.place(relx=0.251, rely=0.455, height=32
                , relwidth=0.701)
        self.sem_annee_specique.configure(values=annee_liste)
        self.sem_annee_specique.current(0)
        
        self.Label2 = tk.Label(self.Frame_option_semestre)
        self.Label2.place(relx=0.072, rely=0.555, height=31, width=50)
        self.Label2.configure(text='''Sem :''')

        self.sem_combox = tk.Combobox(self.Frame_option_semestre,bootstyle="danger")
        self.sem_combox.place(relx=0.251, rely=0.555, height=32
                , relwidth=0.701)
        
        self.sem_combox.configure(values=colonne_semestre)
        self.sem_combox.current(0)

        self.TSeparator2 = tk.Separator(self.Frame_option_semestre)
        self.TSeparator2.place(relx=0.034, rely=0.26,  relwidth=0.928)

        self.TSeparator3 = tk.Separator(self.Frame_option_semestre)
        self.TSeparator3.place(relx=0.055, rely=0.623,  relwidth=0.9)

        self.Button_generer_semestre = tk.Button(self.Frame_option_semestre,bootstyle="outline-success")
        self.Button_generer_semestre.place(relx=0.137, rely=0.732, height=46
                , relwidth=0.75)
        self.Button_generer_semestre.configure(text='''Générer''')

        self.Button_exportation_semestre = tk.Button(self.Frame_option_semestre,bootstyle="outline-info")
        self.Button_exportation_semestre.place(relx=0.137, rely=0.894, height=46
                , relwidth=0.75)
        self.Button_exportation_semestre.configure(text='''Exporter''')

def start_up():
    gui_support.main()

if __name__ == '__main__':
    gui_support.main()




