#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 8.1
#  in conjunction with Tcl version 8.6
#    Oct 06, 2025 02:32:31 PM %z  platform: Windows NT

import sys
import ttkbootstrap as tk
from tkinter import filedialog
from ttkbootstrap.constants import *
from ttkbootstrap.dialogs import *
from lxml import etree
from datetime import datetime
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg
import matplotlib.pyplot as plt
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table,TableStyle
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
import json
import csv
from PIL import Image,ImageTk



import gui

_debug = True # False to eliminate debug printing from callback functions.
#leq variable trés utiliser avec XML
tree_produit=etree.parse("data/dataProduit.xml")
root_produit=tree_produit.getroot()
tree_fournisseur=etree.parse("data/dataFournisseur.xml")
root_fourisseur=tree_fournisseur.getroot()
fourniseurs=root_fourisseur.xpath("//fournisseur")
produits=root_produit.xpath("//produit")
nom_fournisseur=[]

def main(*args):
    global root
    root = tk.Window(themename="darkly")
    root.protocol( 'WM_DELETE_WINDOW' , closer_app)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = gui.Toplevel1(_top1)
    #au demarager de l'application
    #dans l'intervace accueil:
    _w1.Frame_home.tkraise()#mise en avant de l'accueil
    _w1.Frame_find_produit.tkraise()
    _w1.Frame_none.tkraise()
    #la graphique en circulaire pour la repartition des produit
    graphique_circulaire(_w1.Frame_graphe_pie,type_categorie(),data_par_categorie())
    #graphique Evolution des produits
    graphique_courbe(_w1.Frame_grpahe_courbe,type_categorie(),data_par_categorie())
    #pour les 3 bloc information
    _w1.Label_somme_budget.configure(text=str(total_budget())+" AR")
    _w1.Label_nombre_stock_critique.configure(text=nombre_stock_critique()+" Produit(s)")
    ##################################################################
    _w1.Combobox_categorie_produit.configure(values=type_categorie())#on ajoute les type
    _w1.Combobox_categorie_produit.current(0)
    _w1.Combobox_categorie_produit_modifier.configure(values=type_categorie())#on ajoute les type
    #ajouter produit dans chaque tableau corespodant
    ajouter_produit_tableux_inventaire(_w1.table_inventaire)
    ajouter_produit_tableux_inventaire(_w1.table_inventaire_modifier)
    ajouter_produit_tableux_inventaire(_w1.table_inventaire_home)
    #pour ajouter les fournisseur dans le tableau
    ajouter_fournisseur_tableux_fournisseur(_w1.table_fournisseur)
    ajouter_fournisseur_tableux_fournisseur(_w1.table_fournisseur_home)
    #pour choix d'intervarce via au menu
    _w1.menu.bind("<<TreeviewSelect>>",lambda event:menu_choix(event,_w1.menu))
    #Lorsque on clique sur tableau afficher dans les champs
    _w1.table_inventaire.bind("<<TreeviewSelect>>",lambda event:selection_produit(event,_w1.table_inventaire))
    _w1.table_inventaire_modifier.bind("<<TreeviewSelect>>",lambda event:selection_produit_modifier(event,_w1.table_inventaire_modifier))
    #pour ajouter new produit
    _w1.Button_ajouter_produit.configure(command=lambda :ajouter_new_produit(
        _w1.Entry_nom_produit.get(),
        _w1.Combobox_categorie_produit.get(),
        _w1.Spinbox_quantite_produit,
        _w1.Spinbox_prix_produit,
        _w1.Combobox_fournisseur_produit.get(),
        _w1.table_inventaire,
        _w1.table_inventaire_modifier,
        _w1.table_inventaire_home))
    #pour suprimer un produit
    _w1.Button_suprimer_produit.configure(command=lambda:suprimer_un_produit(
                                                                                _w1.table_inventaire,
                                                                                _w1.table_inventaire_modifier,
                                                                                _w1.table_inventaire_home
                                                                             )
                                        )
    #pour modifier un produit
    _w1.Button_modifier_produit.configure(command=lambda:modifier_produit(
        _w1.Entry_nom_produit_modifier.get(),
        _w1.Combobox_categorie_produit_modifier.get(),
        _w1.Spinbox_quantite_produit_modifier,
        _w1.Spinbox_prix_produit_modifier,
        _w1.Combobox_fournisseur_produit_modifier.get(),
        _w1.Combobox_mouvement.get(),
        _w1.Spinbox_stock_mouvement,
        _w1.table_inventaire_modifier,
        _w1.table_inventaire,
        _w1.table_inventaire_home
    ))
    #pour les fournisseur
    #pour recuperer un ligne dans un tableau
    _w1.table_fournisseur.bind("<<TreeviewSelect>>",lambda event:selection_fournisseur(event,_w1.table_fournisseur))
    #ajouter un fournisseur
    _w1.Button_ajouter_fournisseur.configure(command=lambda:add_fourniseur(
        _w1.Entry_nom_fournisseur.get(),
        _w1.Entry_adresse.get(),
        _w1.Entry_telephone.get(),
        _w1.Entry_email.get(),
        _w1.table_fournisseur
    ))
    #modifier un fournisseur
    _w1.Button_modifier_fournisseur.configure(command=lambda:modify_fournisseur(
        _w1.Entry_nom_fournisseur.get(),
        _w1.Entry_adresse.get(),
        _w1.Entry_telephone.get(),
        _w1.Entry_email.get(),
        _w1.table_fournisseur
    ))
    #suprimer un fournisseur
    _w1.Button_suprimer_fournisseur.configure(command=lambda:delete_fournisseur(_w1.table_fournisseur))
    #pour quite l'application
    _w1.Button_quitter.configure(command=closer_app)
    #pour le rapport journalier
    _w1.Button_generer_journalier.configure(command=lambda:generate_rapport(_w1.Combobox_categorie_filtre_rapport.get(),get_option_rapport(),get_date_now(),_w1.Date_jour_specique.get_date()))
    #pour le rapport mensuelle
    _w1.Button_generer_mensuelle.configure(command=lambda:generate_rapport(_w1.Combobox_categorie_filtre_rapport.get(),"mois_specifique",
                                                                           get_date_now(),
                                                                           None,
                                                                           _w1.mois_specique.get(),
                                                                           _w1.moisETannee_specique.get()))
    #pour le rapport annuelle
    _w1.Button_generer_annuelle.configure(command=lambda:generate_rapport(_w1.Combobox_categorie_filtre_rapport.get(),
        "annee_specifique",
        None,
        None,
        None,
        None,
        _w1.annee_specique.get()
    )
                                          )
    #pour le rapport Trimestrielle
    _w1.Button_generer_trimestre.configure(command=lambda:generate_rapport(_w1.Combobox_categorie_filtre_rapport.get(),"trim_specifique",
        None,
        None,
        None,
        None,
        _w1.trim_annee_specique.get(),
        _w1.trim_combox.get()
        ))
    #pour le rapport semestrielle
    _w1.Button_generer_semestre.configure(command=lambda:generate_rapport(_w1.Combobox_categorie_filtre_rapport.get(),"semestre_specifique",
        None,
        None,
        None,
        None,
        _w1.sem_annee_specique.get(),
        None,
        _w1.sem_combox.get()
        ))
    #pour faire les different exportations
    _w1.Button_exportation_journalier.configure(command=lambda:exportation('rapport',None,_w1.table_rapport))
    _w1.Button_exportation_mensuelle.configure(command=lambda:exportation('rapport',None,_w1.table_rapport))
    _w1.Button_exportation_semestre.configure(command=lambda:exportation('rapport',None,_w1.table_rapport))
    _w1.Button_exportation_trimestre.configure(command=lambda:exportation('rapport',None,_w1.table_rapport))
    _w1.Button_exportation_annuelle.configure(command=lambda:exportation('rapport',None,_w1.table_rapport))
    #pour rechercher un produit
    _w1.Label_find_produit.bind('<Button-1>',lambda event:actualiser_produit(event,_w1.Entry_find_produit,
                                                                      _w1.table_inventaire,_w1.table_inventaire_home
                                                                      ,_w1.table_inventaire_modifier
                                                                             ))
    _w1.Entry_find_produit.bind("<KeyRelease>",lambda event:display_produit_find(event,_w1.Entry_find_produit.get()))
    #pour rechercher un fournisseur
    _w1.Label_find_fournisseur.bind('<Button-1>',lambda event:actualiser_fournisseur(event,_w1.Entry_find_fournisseur,
                                                                      _w1.table_fournisseur
                                                                      ,_w1.table_fournisseur_home
                                                                             ))
    _w1.Entry_find_fournisseur.bind("<KeyRelease>",lambda event:display_fournisseur_find(event,_w1.Entry_find_fournisseur.get()))
    ####################################
    #pour filtre le produit
    _w1.Button_filtrer.configure(command=lambda:filter_produit(
        _w1.Combobox_categorie_filtre.get(),
        _w1.table_inventaire,
        _w1.table_inventaire_home,
        _w1.table_inventaire_modifier
          )
        )
    #####################################
    #pour exporter un prodtuis
    _w1.Button_exporter_produit.bind('<Button-1>',lambda event:exportation('produit',_w1.Combobox_categorie_filtre.get(),_w1.table_inventaire))
    #####################################
    #pour exporter les fournisseurs
    _w1.Button_exportation_fournisseur.bind('<Button-1>',lambda event:exportation('fournisseur',None,_w1.table_fournisseur_home))
    #on afficher l'application en permanent
    root.mainloop()


if __name__ == '__main__':
    gui.start_up()

#la logique 
def menu_choix(event,tree_target):#on get le texte de chaque menu selecte
    item=tree_target.selection()
    menu= tree_target.item(item,"text")
    match menu:
        case "Accueil":
            _w1.Frame_home.tkraise()
            #on met a jours le graphique
            update_chart_circulaire(ax_circulaire,canvas_circulaire,type_categorie(),data_par_categorie())
            update_chart_courbe(ax_courbe,canvas_courbe,type_categorie(),data_par_categorie())
            _w1.Frame_none.tkraise()
        case "Inventaire":
            _w1.Frame_Inventaire.tkraise()#mise en avant
            _w1.Frame_find_produit.tkraise()
            _w1.Frame_filtrer_produit.tkraise()
            _w1.Combobox_categorie_filtre.current(0)# om remet le catégrie à tous
        case "Ajouter un produit":
            _w1.Frame_Inventaire_ajouter.tkraise()#mise en avant
            _w1.Button_ajouter_produit.configure(state="normal")#button ajouter produit: active
            _w1.Button_suprimer_produit.configure(state="disabled")#button suprimer produit: désactive
            _w1.Frame_find_produit.tkraise()
            _w1.Frame_filtrer_produit.tkraise()
            _w1.Combobox_categorie_filtre.current(0)# om remet le catégrie à tous
        case "Modifier un produit":
            _w1.Frame_Inventaire_modifier.tkraise()#mise en avant
            _w1.Frame_find_produit.tkraise()
            _w1.Frame_filtrer_produit.tkraise()
            _w1.Combobox_categorie_filtre.current(0)# om remet le catégrie à tous
        case "Suprimer un produit":
            _w1.Frame_Inventaire_ajouter.tkraise()#mise en avant
            _w1.Button_suprimer_produit.configure(state="normal")#button suprimer produit: active
            _w1.Button_ajouter_produit.configure(state="disabled")#button ajouter produit: désactive
            _w1.Frame_find_produit.tkraise()
            _w1.Frame_filtrer_produit.tkraise()
            _w1.Combobox_categorie_filtre.current(0)# om remet le catégrie à tous
        case "Fournisseur":
            _w1.Frame_fournisseur_home.tkraise()#mise en avant
            _w1.Frame_find_fournisseur.tkraise()
            _w1.Frame_expo_fournisseur.tkraise()
        case "Ajouter un fournisseur":
            _w1.Frame_fournisseur.tkraise()#mise en avant
            _w1.Frame_find_fournisseur.tkraise()
            _w1.Button_ajouter_fournisseur.configure(state="normal")#button ajouter fournisseur: active
            _w1.Button_modifier_fournisseur.configure(state="disabled")#button modifier fournisseur: désactive
            _w1.Button_suprimer_fournisseur.configure(state="disabled")#button suprimer fournisseur: désactive 
            _w1.Frame_expo_fournisseur.tkraise()
        case "Modifier un fournisseur":
            _w1.Frame_fournisseur.tkraise()#mise en avant
            _w1.Frame_find_fournisseur.tkraise()
            _w1.Button_ajouter_fournisseur.configure(state="disabled")#button ajouter fournisseur: désactive
            _w1.Button_modifier_fournisseur.configure(state="normal")#button modifier fournisseur: active
            _w1.Button_suprimer_fournisseur.configure(state="disabled")#button suprimer fournisseur: désactive
            _w1.Frame_expo_fournisseur.tkraise()
        case "Suprimer un fournisseur":
            _w1.Frame_fournisseur.tkraise()#mise en avant
            _w1.Frame_find_fournisseur.tkraise()
            _w1.Button_ajouter_fournisseur.configure(state="disabled")#button ajouter fournisseur:désactive
            _w1.Button_modifier_fournisseur.configure(state="disabled")#button modifier fournisseur: désactive
            _w1.Button_suprimer_fournisseur.configure(state="normal")#button suprimer fournisseur: active
            _w1.Frame_expo_fournisseur.tkraise()
        case "Journalier":
            _w1.Frame_rapport.tkraise()#mise en avant
            _w1.Frame_option_jounalier.tkraise()#mise en avant
            clear_treeview(_w1.table_rapport)#on vide le tableaux
            _w1.Frame_filtrer_produit_rapport.tkraise()
            _w1.Combobox_categorie_filtre_rapport.current(0)# om remet le catégrie à tous
            _w1.Frame_find_vide.tkraise()
        case "Mensuelle":
            _w1.Frame_rapport.tkraise()#mise en avant
            _w1.Frame_option_mensuelle.tkraise()#mise en avant
            clear_treeview(_w1.table_rapport)#on vide le tableaux
            _w1.Frame_filtrer_produit_rapport.tkraise()
            _w1.Combobox_categorie_filtre_rapport.current(0)# om remet le catégrie à tous
            _w1.Frame_find_vide.tkraise()
        case "Annuelle":
            _w1.Frame_rapport.tkraise()#mise en avant
            _w1.Frame_option_annuelle.tkraise()#mise en avant
            clear_treeview(_w1.table_rapport)#on vide le tableaux
            _w1.Frame_filtrer_produit_rapport.tkraise()
            _w1.Combobox_categorie_filtre_rapport.current(0)# om remet le catégrie à tous
            _w1.Frame_find_vide.tkraise()
        case "Trimestre":
            _w1.Frame_rapport.tkraise()#mise en avant
            _w1.Frame_option_trimestre.tkraise()#mise en avant
            clear_treeview(_w1.table_rapport)#on vide le tableaux
            _w1.Frame_filtrer_produit_rapport.tkraise()
            _w1.Combobox_categorie_filtre_rapport.current(0)# om remet le catégrie à tous
            _w1.Frame_find_vide.tkraise()
        case "Semestre":
            _w1.Frame_rapport.tkraise()#mise en avant
            _w1.Frame_option_semestre.tkraise()#mise en avant
            clear_treeview(_w1.table_rapport)#on vide le tableaux
            _w1.Frame_filtrer_produit_rapport.tkraise()
            _w1.Combobox_categorie_filtre_rapport.current(0)# om remet le catégrie à tous
            _w1.Frame_find_vide.tkraise()


#pour recuperer un fournisseur
def recuperer_fournisseur():
    for f in fourniseurs:
        nom_fournisseur.append(f.find('nom_fournisseur').text)
    return nom_fournisseur


#pour filtrer un produit
def filter_produit(option,tab_produit1,tab_produit2,tab_produit3):
    match option:
        case 'Tous':
            ajouter_produit_tableux_inventaire(tab_produit1)
            ajouter_produit_tableux_inventaire(tab_produit2)
            ajouter_produit_tableux_inventaire(tab_produit3)
        case 'Électronique':
            ajouter_produit_tableux_inventaire_filtre(tab_produit1,option)
            ajouter_produit_tableux_inventaire_filtre(tab_produit2,option)
            ajouter_produit_tableux_inventaire_filtre(tab_produit3,option)
        case 'Fourniture':
            ajouter_produit_tableux_inventaire_filtre(tab_produit1,option)
            ajouter_produit_tableux_inventaire_filtre(tab_produit2,option)
            ajouter_produit_tableux_inventaire_filtre(tab_produit3,option)
        case 'PPN':
            ajouter_produit_tableux_inventaire_filtre(tab_produit1,option)
            ajouter_produit_tableux_inventaire_filtre(tab_produit2,option)
            ajouter_produit_tableux_inventaire_filtre(tab_produit3,option)
        case "Accésoire":
            ajouter_produit_tableux_inventaire_filtre(tab_produit1,option)
            ajouter_produit_tableux_inventaire_filtre(tab_produit2,option)
            ajouter_produit_tableux_inventaire_filtre(tab_produit3,option)
        case "Boisson":
            ajouter_produit_tableux_inventaire_filtre(tab_produit1,option)
            ajouter_produit_tableux_inventaire_filtre(tab_produit2,option)
            ajouter_produit_tableux_inventaire_filtre(tab_produit3,option)
        case "Textille":
            ajouter_produit_tableux_inventaire_filtre(tab_produit1,option)
            ajouter_produit_tableux_inventaire_filtre(tab_produit2,option)
            ajouter_produit_tableux_inventaire_filtre(tab_produit3,option)


#pour ajouter les produit dans un tableux produit cible filtre
def ajouter_produit_tableux_inventaire_filtre(tab,categorie):
    clear_treeview(tab)
    prods=root_produit.xpath(f"//produit[catégorie='{categorie}']")
    for prod in prods:
        nom=prod.find('nom').text
        categorie=prod.find('catégorie').text
        quantite=prod.find('quantite').text
        prix=prod.find('prix').text
        nom_f=prod.find('fournisseur').text
        if tab==_w1.table_inventaire:
           date=prod.find('date_ajoute').text
        else:
            date=prod.find('date_modification').text
        sorties=prod.xpath("mouvement[@type='Sortie']/text()")#on recuperer chaque sortie
        entres=prod.xpath(f"mouvement[@type='Entre']/text()")#on recuparer chaque entre
        stock_actuelle=(int(quantite)+sum(liste_to_int(entres)))-sum(liste_to_int(sorties))#on calcule lestock actuelle
        tab.insert("","end",value=(nom,categorie,stock_actuelle,prix,nom_f,date))


#pour ajouter les produit dans un tableux produit cible
def ajouter_produit_tableux_inventaire(tab):
    clear_treeview(tab)
    for prod in produits:
        nom=prod.find('nom').text
        categorie=prod.find('catégorie').text
        quantite=prod.find('quantite').text
        prix=prod.find('prix').text
        nom_f=prod.find('fournisseur').text
        if tab==_w1.table_inventaire:
           date=prod.find('date_ajoute').text
        else:
            date=prod.find('date_modification').text
        sorties=prod.xpath("mouvement[@type='Sortie']/text()")#on recuperer chaque sortie
        entres=prod.xpath(f"mouvement[@type='Entre']/text()")#on recuparer chaque entre
        stock_actuelle=(int(quantite)+sum(liste_to_int(entres)))-sum(liste_to_int(sorties))#on calcule lestock actuelle
        tab.insert("","end",value=(nom,categorie,stock_actuelle,prix,nom_f,date))


def ajouter_fournisseur_tableux_fournisseur(tab):
    clear_treeview(tab)
    for f in fourniseurs:
        nom=f.find('nom_fournisseur').text
        adresse=f.find('adresse').text
        tel=f.find('télèphone').text
        email=f.find('email').text
        date=f.find('date').text
        tab.insert("","end",value=(nom,adresse,tel,email,date))


def type_categorie():
    liste=["Électronique","Fourniture","PPN","Textille","Accésoire","Boisson"]
    return  liste


def nombre_ID_BD(rootx,requette):#methode pour recupere le nombre d'id dans la base xml
     r=rootx.xpath(f'count({requette})')
     return  int(r)


def ajouter_new_produit(nom_prod,categorie,quantie,prix,nom_fouriseur,tab1,tab2,tab3):#methode pour ajouter nouvelle produit
    if nom_prod=="" or categorie=="" or quantie.get()=="" or prix.get()=="" or nom_fouriseur=="":
        Messagebox.show_error(title="Erreur!",message="Veuiller bien remplirer la formulaire ")
    else:
        if( quantie.get().isdigit() and prix.get().isdigit()):
                res=Messagebox.yesnocancel(title="Question",message=f"Voulez-vous vraiment enregistre le produit {nom_prod} ?")
                if res=="Yes":
                    produit_db = root_produit.xpath(f"//produit[nom='{nom_prod}']")
                    if len(produit_db)>0:
                        Messagebox.show_warning(title="Attention!",message=f"Le produit {nom_prod} existe deja dans la base de donnée")
                    else:
                            if quantie!=0 or prix!=0:
                                id_produit = nombre_ID_BD(root_produit,'//produit')
                                id_produit += 1
                                new_produit = etree.Element("produit", id_produit=str(id_produit))
                                etree.SubElement(new_produit, "date_ajoute").text = get_date_now()
                                etree.SubElement(new_produit, "date_modification").text = get_date_now()
                                etree.SubElement(new_produit, "nom").text = nom_prod
                                etree.SubElement(new_produit, "catégorie").text = categorie
                                etree.SubElement(new_produit, "quantite").text = str(quantie.get())
                                etree.SubElement(new_produit, "prix").text = str(prix.get())
                                etree.SubElement(new_produit, "fournisseur").text = nom_fouriseur
                                # on ajoute dans le root correspodant
                                root_produit.append(new_produit)
                                # on savegarder
                                tree_produit.write("data/dataProduit.xml", encoding="utf-8", pretty_print=True, xml_declaration=True)
                                # on ajouter dans le tableaux
                                tab1.insert("", "end", value=(nom_prod, categorie, quantie.get(), prix.get(), nom_fouriseur,get_date_now()))
                                tab2.insert("", "end", value=(nom_prod, categorie, quantie.get(), prix.get(), nom_fouriseur,get_date_now()))
                                tab3.insert("", "end", value=(nom_prod, categorie, quantie.get(), prix.get(), nom_fouriseur,get_date_now()))
                                # on vide les champs
                                clean_formulaire_inventaire_1()
                                #on fait mise a jours le bloc d'information
                                _w1.Label_somme_budget.configure(text=str(total_budget())+" AR")
                                _w1.Label_nombre_stock_critique.configure(text=nombre_stock_critique()+" Produit(s)")
                                Messagebox.show_info(title="Infomation",message=f"Le produit: {nom_prod} à étè enregistre avec succée!")
                elif res=="No":
                    #on fait rien
                    pass
                else:
                    # on vide les champs
                    clean_formulaire_inventaire_1()
        else:
             Messagebox.show_error(title="Erreur",message=f"Pour le prix et le quantite veuiller entre des nombres svp!")


def clear_treeview(tab):#methode pour vide un tableaux
    for items in tab.get_children():
        tab.delete(items)


def changer_scene(frame):#pour changer de scene ou frame
    frame.tkraise()#met un frame au dessous des autre


def liste_produit():
    liste=[]
    for p in produits:
        nom_produit = p.find('nom_produit').text
        liste.append(nom_produit)
    return liste


def stock_produit():
    liste=[]
    for p in produits:
        qt =int( p.find('quantite').text)
        liste.append(qt)
    return liste


def clean_formulaire_inventaire_1():#methode pour remetre les formulaire vide
    _w1.Entry_nom_produit.delete(0,'end')
    _w1.Combobox_categorie_produit.delete(0,'end')
    _w1.Spinbox_quantite_produit.delete(0,'end')
    _w1.Spinbox_prix_produit.delete(0,'end')
    _w1.Combobox_fournisseur_produit.delete(0,'end')


def clean_formulaire_inventaire_2():#methode pour remetre les formulaire vide
    _w1.Entry_nom_produit_modifier.delete(0,'end')
    _w1.Combobox_categorie_produit_modifier.delete(0,'end')
    _w1.Spinbox_quantite_produit_modifier.delete(0,'end')
    _w1.Spinbox_prix_produit_modifier.delete(0,'end')
    _w1.Spinbox_stock_mouvement.delete(0,'end')
    _w1.Combobox_mouvement.delete(0,'end')
    _w1.Combobox_fournisseur_produit_modifier.delete(0,'end')


def selection_ligne_tableaux(tab):#methode pour avoir la produit,... et l'item du tableaux correspodant
    #pour la modification on met on avant mouvement aucun
    _w1.Combobox_mouvement.current(0)
    selected=tab.selection()

    for item in selected:
        value=tab.item(item,"value")
        return value,item # je retouner le produit et son item de tableaux


def suprimer_un_produit(tab1,tab2,tab3):#Methodes pour surpimer un produit
    selected=tab1.selection()
    if not selected:
        Messagebox.show_info(title="Information",message='Veuiller selectioner une ligne svp!')
    else:
        res=Messagebox.yesno(title="Question",message="Voulez-vous suprimer le produit definitivement ?")
        if res=="Yes":
            produit,item=selection_ligne_tableaux(tab1)# je recuper la produit selection et son item dans le tableau
            produit_db=root_produit.xpath(f"//produit[nom='{produit[0]}']")
            if produit_db:
                root_produit.remove(produit_db[0])# on delete dans la base donnee
                #on savegarde cette modification
                tree_produit.write("data/dataProduit.xml", encoding="utf-8", pretty_print=True, xml_declaration=True)
                tab1.delete(item)#on efface dans le tableau
                tab2.delete(item)#on efface dans le tableau
                tab3.delete(item)#on efface dans le tableau
                #on vide le champs
                clean_formulaire_inventaire_1()
        else:#sinon, on fait rien
            pass


def selection_produit(event,tab):#mtehodes pour selection un produit et l'afficher dans la formulaire
    clean_formulaire_inventaire_1()#on vide d'abord
    produit,item=selection_ligne_tableaux(tab)# je recuper la produit selection et son item dans le tableau
    #on ajouter
    _w1.Entry_nom_produit.insert(0,produit[0])#nom du produit
    _w1.Combobox_categorie_produit.insert(0,produit[1])#categorie du produit
    _w1.Spinbox_quantite_produit.insert(0, produit[2])#quantite du produit
    _w1.Spinbox_prix_produit.insert(0, produit[3])#prix du produit
    _w1.Combobox_fournisseur_produit.insert(0, produit[4])#fournisseur du produit

def selection_produit_modifier(event,tab):#mtehodes pour selection un produit et l'afficher dans la formulaire
    _w1.Spinbox_quantite_produit_modifier.configure(state="normal")
    clean_formulaire_inventaire_2()#on vide d'abord
    produit,item=selection_ligne_tableaux(tab)# je recuper la produit selection et son item dans le tableau
    #on ajouter
    _w1.Entry_nom_produit_modifier.insert(0,produit[0])#nom du produit
    _w1.Combobox_categorie_produit_modifier.insert(0,produit[1])#categorie du produit
    _w1.Spinbox_quantite_produit_modifier.insert(0, produit[2])#quantite du produit
    _w1.Spinbox_prix_produit_modifier.insert(0, produit[3])#prix du produit
    _w1.Combobox_fournisseur_produit_modifier.insert(0, produit[4])#fournisseur du produit
    _w1.Spinbox_quantite_produit_modifier.configure(state="disabled")


def modifier_produit(new_nom_produit,new_categorie,new_quantite,new_prix,new_fournisseur,mouvement,stock_mouvement,tab1,tab2,tab3):#methodes pour modifier un produit selecionner
    selected=tab1.selection()
    if not selected:
        Messagebox.show_info(title="Information",message='Veuiller selectioner une ligne svp!')
    else:
        if(new_quantite.get().isdigit() and new_prix.get().isdigit()):
                res=Messagebox.yesno(title="Question",message="Voulez-vous vraiment modifier le produit ?")
                if res=="Yes":
                        produit, item_produit = selection_ligne_tableaux(tab1)  # je recuper la produit selection et son item dans le tableau
                        produit_db = root_produit.xpath(f"//produit[nom='{produit[0]}']")
                        if produit_db:
                                produit_db[0].find('date_modification').text = get_date_now()
                                produit_db[0].find('nom').text = new_nom_produit
                                produit_db[0].find('catégorie').text = new_categorie
                                stock_initale=produit_db[0].find('quantite').text
                                produit_db[0].find('prix').text = str(new_prix.get())
                                produit_db[0].find('fournisseur').text = new_fournisseur
                                date_ajoute=produit_db[0].find('date_ajoute').text
                                if mouvement=="Aucun":#aucun mouvement
                                    #on modififie la quantite initiale
                                    produit_db[0].find('quantite').text = new_quantite.get()
                                    # on savegarde apres
                                    tree_produit.write("data/dataProduit.xml", encoding="utf-8", pretty_print=True, xml_declaration=True)
                                    # on modifier aussi dans le tableau
                                     # on modifier aussi dans le tableau
                                    tab1.item(item_produit, values=(
                                            new_nom_produit,
                                            new_categorie,
                                            new_quantite.get(),
                                            new_prix.get(),
                                            new_fournisseur,
                                            get_date_now()
                                        ))
                                    tab2.item(item_produit, values=(
                                            new_nom_produit,
                                            new_categorie,
                                            new_quantite.get(),
                                            new_prix.get(),
                                            new_fournisseur,
                                            date_ajoute
                                        ))
                                    tab3.item(item_produit, values=(
                                            new_nom_produit,
                                            new_categorie,
                                            new_quantite.get(),
                                            new_prix.get(),
                                            new_fournisseur,
                                            date_ajoute
                                        ))
                                    # on vide les champ
                                    clean_formulaire_inventaire_2()
                                elif mouvement=="Entre":#mouvment entre de stock
                                    if(stock_mouvement.get().isdigit() and stock_mouvement.get()!=""):
                                            new_mouvement=etree.Element("mouvement",type=mouvement,date=get_date_now())#on creer un mouvement
                                            new_mouvement.text=str(stock_mouvement.get())#on ajoute la valeur au mouvement
                                            produit_db[0].append(new_mouvement)#on ajoute dans l'arbre
                                            # on savegarde apres
                                            tree_produit.write("data/dataProduit.xml", encoding="utf-8", pretty_print=True, xml_declaration=True)

                                            sorties=produit_db[0].xpath("mouvement[@type='Sortie']/text()")#on recuperer chaque sortie
                                            entres=produit_db[0].xpath(f"mouvement[@type='{mouvement}']/text()")#on recuparer chaque entre
                                            stock_actuelle=(int(stock_initale)+sum(liste_to_int(entres)))-sum(liste_to_int(sorties))#on calcule les tock actuelle
                                            # on modifier aussi dans le tableau
                                            tab1.item(item_produit, values=(
                                                    new_nom_produit,
                                                    new_categorie,
                                                    stock_actuelle,
                                                    new_prix.get(),
                                                    new_fournisseur,
                                                    get_date_now()
                                                ))
                                            tab2.item(item_produit, values=(
                                                    new_nom_produit,
                                                    new_categorie,
                                                    stock_actuelle,
                                                    new_prix.get(),
                                                    new_fournisseur,
                                                    date_ajoute
                                                ))
                                            tab3.item(item_produit, values=(
                                                    new_nom_produit,
                                                    new_categorie,
                                                    stock_actuelle,
                                                    new_prix.get(),
                                                    new_fournisseur,
                                                    date_ajoute
                                                ))
                                            # on vide les champ
                                            clean_formulaire_inventaire_2()
                                            #on fait mise a jours le bloc d'information
                                            _w1.Label_somme_budget.configure(text=str(total_budget())+" AR")
                                            _w1.Label_nombre_stock_critique.configure(text=nombre_stock_critique()+" Produit(s)")
                                            #on mets ajours l'information sur le mouvement de stoks
                                            _w1.Label_nombre_entre.configure(text=f"Entre : {total_entre_sortie_today()[0]} produit(s)")
                                    else:
                                         Messagebox.show_error(title="Erreur",message=f"Pour le stock mouvement: veuiller entre des nombres svp! et bien remplirer le champ")
                                elif mouvement=="Sortie":#mouvement sortie de stock
                                    if(stock_mouvement.get().isdigit() and stock_mouvement.get()!=""):
                                                stock=int(stock_mouvement.get())
                                                qt=int(_w1.Spinbox_quantite_produit_modifier.get())
                                                #on teste si le stock sortant est superieur au stock actuelle
                                                if qt<stock:
                                                    Messagebox.show_error(title="Erreur",message="Stock sortant supérieur au stock actuelle!")
                                                else:

                                                    new_mouvement=etree.Element("mouvement",type=mouvement,date=get_date_now())#on creer un mouvement
                                                    new_mouvement.text=str(stock_mouvement.get())#on ajoute la valeur au mouvement
                                                    produit_db[0].append(new_mouvement)#on ajoute dans l'arbre
                                                    # on savegarde apres
                                                    tree_produit.write("data/dataProduit.xml", encoding="utf-8", pretty_print=True, xml_declaration=True)
                                                    #on fait le calcule du stock
                                                    sorties=produit_db[0].xpath(f"mouvement[@type='{mouvement}']/text()")#on recuperer chaque sortie
                                                    entres=produit_db[0].xpath("mouvement[@type='Entre']/text()")#on recuparer chaque entre
                                                    stock_actuelle=(int(stock_initale)+sum(liste_to_int(entres)))-sum(liste_to_int(sorties))#on calcule lestock actuelle
                                                    # on modifier aussi dans le tableau
                                                    tab1.item(item_produit, values=(
                                                        new_nom_produit,
                                                        new_categorie,
                                                        stock_actuelle,
                                                        new_prix.get(),
                                                        new_fournisseur,
                                                        get_date_now()
                                                    ))
                                                    tab2.item(item_produit, values=(
                                                        new_nom_produit,
                                                        new_categorie,
                                                        stock_actuelle,
                                                        new_prix.get(),
                                                        new_fournisseur,
                                                        date_ajoute
                                                    ))
                                                    tab3.item(item_produit, values=(
                                                        new_nom_produit,
                                                        new_categorie,
                                                        stock_actuelle,
                                                        new_prix.get(),
                                                        new_fournisseur,
                                                        date_ajoute
                                                    ))
                                                    # on vide les champ
                                                    clean_formulaire_inventaire_2()
                                                    #on fait mise a jours le bloc d'information
                                                    _w1.Label_somme_budget.configure(text=str(total_budget())+" AR")
                                                    _w1.Label_nombre_stock_critique.configure(text=nombre_stock_critique()+" Produit(s)")
                                                    #on mets ajours l'information sur le mouvement de stoks
                                                    _w1.Label_nombre_sortie.configure(text=f"Sortie : {total_entre_sortie_today()[1]} produit(s)")
                                    else:
                                         Messagebox.show_error(title="Erreur",message=f"Pour le stock mouvement: veuiller entre des nombres svp! et bien remplirer le champ")    
                else:#sinon,on fait rien
                    pass
        else:
            Messagebox.show_error(title="Erreur",message=f"Pour le prix: veuiller entre des nombres svp!")

def get_date_now():#methode pour avoir la date de format jour/mois/annee = 29/09/2025
    curent_date = datetime.now()
    date = curent_date.strftime("%Y-%m-%d")# annee/mois/jour
    return date


#La logique pour le founisseur
def add_fourniseur(nom,adresse,telephone,email,tab):
    res=Messagebox.yesnocancel(title="Question",message=f"Voulez vous ajouter le fournisseur qui s'appelle {nom} ?")
    if res=="Yes":
            fournisseur_db = root_fourisseur.xpath(f"//fournisseur[nom_fournisseur='{nom}']")
            #on test si le founisseur existe deja
            if len(fournisseur_db)>0:
                Messagebox.show_warning(title="Antention",message=f"le fournisseur qui s'appelle {nom} existe déja!",parent=root)
            else:#sinon
                id= nombre_ID_BD(root_fourisseur, '//fournisseur')
                id+= 1  # on ajoute un a l'i
                new_founisseur=etree.Element("fournisseur",id_fournisseur=str(id))
                etree.SubElement(new_founisseur,"nom_fournisseur").text=nom
                etree.SubElement(new_founisseur, "adresse").text = adresse
                etree.SubElement(new_founisseur, "télèphone").text = telephone
                etree.SubElement(new_founisseur, "email").text = email
                etree.SubElement(new_founisseur, "date").text = get_date_now()
                #on ajoute dans l'arbre xml
                root_fourisseur.append(new_founisseur)
                #on save dans la base de donner
                tree_fournisseur.write("data/dataFournisseur.xml", encoding="utf-8", pretty_print=True, xml_declaration=True)
                #on afficher dans le tableau
                tab.insert("","end",value=(
                    nom,
                    adresse,
                    telephone,
                    email,
                    get_date_now()
                ))
                # on met ajoute les combobox associe
                nom_fournisseur.append(nom)
                #on effectue les mise à jours
                update_combobox(_w1.Combobox_fournisseur_produit,nom_fournisseur)
                update_combobox(_w1.Combobox_fournisseur_produit_modifier,_w1.Combobox_fournisseur_produit['values'])
                #on vide les champs
                clean_champ_founisseur()
                #on afficher un messager de succe!
                Messagebox.show_info(title="Information",message=f"le fournisseur qui s'appelle {nom} a étè enregistre avec succée!",parent=root)
    elif res=="No":
        #on fait rien
        pass
    else:
        clean_champ_founisseur()
    

def update_combobox(combo,valeur):#methode pour metre a jour un combobox
    #on vide d'abords
    combo['values']=[]
    #on ajoute la nouvelle valeur
    combo['values']=valeur


#methodes pour supprimer un fournisseur
def delete_fournisseur(tab):
    selected=tab.selection()
    if not selected:
        Messagebox.show_info(title="Information",message='Veuiller selectioner une ligne svp!')
    else:
        res=Messagebox.yesno(title="Question",message="Voulez vous vraiment supprimet ce fournisseur ?")
        if res=="Yes":
            founisseur_selected,item=selection_ligne_tableaux(tab)#je recuperer le fournisseur et son item
            fourniseur=root_fourisseur.xpath(f"//fournisseur[nom_fournisseur='{founisseur_selected[0]}']")
            if fourniseur:
                root_fourisseur.remove(fourniseur[0])#on suprimer dans la base
                # on save dans la base de donner
                tree_fournisseur.write("data/dataFournisseur.xml", encoding="utf-8", pretty_print=True, xml_declaration=True)
                #on suprimer dans le tableau
                tab.delete(item)
                # on met ajoute les combobox associe
                #on vide les combobox
                nom_fournisseur.remove(founisseur_selected[0])
                #on effectue les mise à jours
                update_combobox(_w1.Combobox_fournisseur_produit,nom_fournisseur)
                update_combobox(_w1.Combobox_fournisseur_produit_modifier,_w1.Combobox_fournisseur_produit['values'])
                #on vide les champs
                clean_champ_founisseur()
        else:
            #on fait rien
            pass


#pour vide les champs fournisseur
def clean_champ_founisseur():
    _w1.Entry_nom_fournisseur.delete(0,"end")
    _w1.Entry_adresse.delete(0, "end")
    _w1.Entry_telephone.delete(0, "end")
    _w1.Entry_email.delete(0, "end")


def modify_fournisseur(nom,adresse,telephone,email,tab):
    selected=tab.selection()
    if not selected:
        Messagebox.show_info(title="Information",message='Veuiller selectioner une ligne svp!')
    else:
        res=Messagebox.yesno(title="Question",message=f"Voulez-vous vraiment modifier le founisseur qui s'appelle {nom}")
        if res=="Yes":
            founisseur_selected, item = selection_ligne_tableaux(tab)  # je recuperer le fournisseur et son item
            fournisseur_db = root_fourisseur.xpath(f"//fournisseur[nom_fournisseur='{founisseur_selected[0]}']")
            if fournisseur_db:
                fournisseur_db[0].find('nom_fournisseur').text=nom
                fournisseur_db[0].find('adresse').text = adresse
                fournisseur_db[0].find('télèphone').text = telephone
                fournisseur_db[0].find('email').text = email
                fournisseur_db[0].find('date').text = get_date_now()
                #on save la modification
                tree_fournisseur.write("data/dataFournisseur.xml", encoding="utf-8", pretty_print=True, xml_declaration=True)
                #on modifier aussi dans le tableau
                tab.item(item,values=(
                    nom,
                    adresse,
                    telephone,
                    email,
                    get_date_now()
                ))
                # on met ajoute les combobox associe
                if founisseur_selected[0] in nom_fournisseur:
                   index=nom_fournisseur.index(founisseur_selected[0])
                   nom_fournisseur[index]=nom
                #on effectue les mise à jours
                update_combobox(_w1.Combobox_fournisseur_produit,nom_fournisseur)
                update_combobox(_w1.Combobox_fournisseur_produit_modifier,_w1.Combobox_fournisseur_produit['values'])
                #on vide les champs
                clean_champ_founisseur()
        else:#on fait rein
            pass
    

def selection_fournisseur(event,tab):#mthodes pour selection un produit et l'afficher dans la formulaire
    clean_champ_founisseur()#on vide d'abord
    fournisseur,item=selection_ligne_tableaux(tab)# je recuper la fournisseur selection et son item dans le tableau
    #on ajouter
    _w1.Entry_nom_fournisseur.insert(0,fournisseur[0])#nom du fournisseur
    _w1.Entry_adresse.insert(0, fournisseur[1])#adresse du fournisseur
    _w1.Entry_telephone.insert(0, fournisseur[2])#telephone du fournisseur
    _w1.Entry_email.insert(0, fournisseur[3])#email du fournisseur


def liste_to_int(liste):#methode pour modifier un liste d'string en int
    l=[]
    for x in liste:
        l.append(int(x))
    return l


def graphique_circulaire(master_root,label,donnee):#metode pour creer un graphique Pie ou circulaire
    global fig_circulaire,ax_circulaire,canvas_circulaire
    fig_circulaire,ax_circulaire=plt.subplots()
    ax_circulaire.pie(donnee,labels=label,autopct='%1.1f%%')
    ax_circulaire.set_title("Répartition des produits")
    canvas_circulaire = FigureCanvasTkAgg(fig_circulaire, master=master_root)
    canvas_circulaire.draw()
    canvas_circulaire.get_tk_widget().pack()


def update_chart_circulaire(ax,canvas,label,donnee):#methode pour modifier le graphique circulaire
    ax.clear()#on vides les donner
    ax.pie(donnee,labels=label,autopct='%1.1f%%')
    ax.set_title("Répartition des produits")
    canvas.draw()


def data_par_categorie():#methodes pour avoire le nombre de catégorie par type
    data=[]
    for catg in type_categorie():
        res=root_produit.xpath(f"count(//produit[catégorie='{catg}'])")
        data.append(int(res))
    return data

def graphique_courbe(master_root,dataX,dataY):#metode pour creer un graphique Pie ou circulaire
    global fig_courbe,ax_courbe,canvas_courbe
    fig_courbe,ax_courbe=plt.subplots()
    ax_courbe.plot(dataX,dataY,marker="o")
    ax_courbe.set_title("Évolution des produits")
    ax_courbe.set_xlabel("Catégorie")
    ax_courbe.set_ylabel("Nombre de produits")
    canvas_courbe = FigureCanvasTkAgg(fig_courbe, master=master_root)
    canvas_courbe.draw()
    canvas_courbe.get_tk_widget().pack()


def update_chart_courbe(ax,canvas,dataX,dataY):#pour modifier le graphique courbe
    ax.clear()#on vides les donner
    ax.plot(dataX,dataY,marker="o")
    ax.set_title("Évolution des produits")
    ax.set_xlabel("Catégorie")
    ax.set_ylabel("Nombre de produits")
    canvas.draw()


def total_budget():#methode pour avoire la total des produit fois(x) leur prix chacun
    stock_total=[]
    for prod in produits:
        quantite=prod.find('quantite').text
        prix=prod.find('prix').text
        sorties=prod.xpath("mouvement[@type='Sortie']/text()")#on recuperer chaque sortie
        entres=prod.xpath(f"mouvement[@type='Entre']/text()")#on recuparer chaque entre
        stock_actuelle=(int(quantite)+sum(liste_to_int(entres)))-sum(liste_to_int(sorties))#on calcule lestock actuelle
        stock_total.append(stock_actuelle*int(prix))
    return sum(stock_total)


def nombre_stock_critique():#methodes pour avoir le nombre de produit<=25
    compteur=0
    for prod in produits:
        quantite=prod.find('quantite').text
        sorties=prod.xpath("mouvement[@type='Sortie']/text()")#on recuperer chaque sortie
        entres=prod.xpath(f"mouvement[@type='Entre']/text()")#on recuparer chaque entre
        stock_actuelle=(int(quantite)+sum(liste_to_int(entres)))-sum(liste_to_int(sorties))#on calcule les tock actuelle
        if stock_actuelle<=25:
            compteur+=1
        if compteur==0:
            _w1.Label_stockCritique.configure(image=_w1.icone_happy)
        else:
            _w1.Label_stockCritique.configure(image=_w1.icone_sad)
    return str(compteur)


def get_taill_ecran():#pour obtenire la largeur et le hauteur d'un ecran
    width=root.winfo_screenwidth()
    height=root.winfo_screenheight()
    return width,height


def closer_app():#methode pour ferme l'application
    res=Messagebox.yesno(title="Question",message="Voulez-vous quitter l'application ?")
    if res=="Yes":
        plt.close('all')#on ferme tous les graphique
        root.destroy()#on fermer la fenetre
    else:#sinon
        #on fait rien
        pass
    

#Pour les rapports
def generate_rapport(categorie_produit,option,date_now=None,jour_specique=None,mois_specique=None,moiETanne=None,anne_specique=None,trimestre_specifique=None,semestre_specifique=None):
    clear_treeview(_w1.table_rapport)#on vide d'abord le tableau
    format="%Y-%m-%d"
    global option_rapport,date_target# variable globale
    #on test les option du rapport
    match option:
        case "jour_now":
            entre_xpath=f"mouvement[@type='Entre' and @date='{date_now}']/text()"
            sortie_xpath=f"mouvement[@type='Sortie' and @date='{date_now}']/text()"
            for prod in produits:
                nom_produit=prod.find('nom').text
                quantite=int(prod.find('quantite').text)
                entres=prod.xpath(entre_xpath)
                sorties=prod.xpath(sortie_xpath)
                total_entre=sum(liste_to_int(entres))
                total_sortie=sum(liste_to_int(sorties))
                stock_finale=(quantite+total_entre)-total_sortie
                if stock_finale==0:
                    commentaire="Stock épuisse"
                elif stock_finale<=25:
                    commentaire="Stock critique"
                elif stock_finale>25 and stock_finale<=250:
                    commentaire="Stock bon"
                elif stock_finale>250:
                     commentaire="Sur stock"
                #on test si l'utilisateur a choisier un catégorie specifique
                if categorie_produit=="Tous": 
                    if total_entre>0 or total_sortie>0:# on affiche seulement les produit qui a des mouvements
                        _w1.table_rapport.insert("","end",values=(nom_produit,quantite,total_entre,total_sortie,stock_finale,commentaire))
                elif prod.find('catégorie').text==categorie_produit:
                    if total_entre>0 or total_sortie>0:# on affiche seulement les produit qui a des mouvements
                        _w1.table_rapport.insert("","end",values=(nom_produit,quantite,total_entre,total_sortie,stock_finale,commentaire))
                #on teste si le tableaux est vide
            if getTableauItems(_w1.table_rapport)==[]:
                 Messagebox.show_info(title="Information",message="Aucun mouvement du stock: d'ou pas de rapport a génerer!")
            #on changer les variables
            option_rapport=option
            date_target=date_now
        case "jour_specifique":
            jour=format_date(jour_specique,str(format))
            entre_xpath=f"mouvement[@type='Entre' and @date='{jour}']/text()"
            sortie_xpath=f"mouvement[@type='Sortie' and @date='{jour}']/text()"
            for prod in produits:
                nom_produit=prod.find('nom').text
                quantite=int(prod.find('quantite').text)
                entres=prod.xpath(entre_xpath)
                sorties=prod.xpath(sortie_xpath)
                total_entre=sum(liste_to_int(entres))
                total_sortie=sum(liste_to_int(sorties))
                stock_finale=(quantite+total_entre)-total_sortie
                if stock_finale==0:
                    commentaire="Stock épuisse"
                elif stock_finale<=25:
                    commentaire="Stock critique"
                elif stock_finale>25 and stock_finale<=250:
                    commentaire="Stock bon"
                elif stock_finale>250:
                     commentaire="Sur stock"
                #on test si l'utilisateur a choisier un catégorie specifique
                if categorie_produit=="Tous": 
                    if total_entre>0 or total_sortie>0:# on affiche seulement les produit qui a des mouvements
                        _w1.table_rapport.insert("","end",values=(nom_produit,quantite,total_entre,total_sortie,stock_finale,commentaire))
                elif prod.find('catégorie').text==categorie_produit:
                    if total_entre>0 or total_sortie>0:# on affiche seulement les produit qui a des mouvements
                        _w1.table_rapport.insert("","end",values=(nom_produit,quantite,total_entre,total_sortie,stock_finale,commentaire))
                #on teste si le tableaux est vide
            if getTableauItems(_w1.table_rapport)==[]:
                 Messagebox.show_info(title="Information",message="Aucun mouvement du stock: d'ou pas de rapport a génerer!")
            #on changer les variables
            option_rapport=option
            date_target=jour
        case "mois_specifique":
            mois_cible=moiETanne+"-"+mois_lettreTO_chiffre(mois_specique)
            entre_xpath=f"mouvement[@type='Entre' and  starts-with(@date,'{mois_cible}')]/text()"
            sortie_xpath=f"mouvement[@type='Sortie' and  starts-with(@date,'{mois_cible}')]/text()"
            for prod in produits:
                nom_produit=prod.find('nom').text
                quantite=int(prod.find('quantite').text)
                entres=prod.xpath(entre_xpath)
                sorties=prod.xpath(sortie_xpath)
                total_entre=sum(liste_to_int(entres))
                total_sortie=sum(liste_to_int(sorties))
                stock_finale=(quantite+total_entre)-total_sortie
                if stock_finale==0:
                    commentaire="Stock épuisse"
                elif stock_finale<=25:
                    commentaire="Stock critique"
                elif stock_finale>25 and stock_finale<=250:
                    commentaire="Stock bon"
                elif stock_finale>250:
                     commentaire="Sur stock"
                #on test si l'utilisateur a choisier un catégorie specifique
                if categorie_produit=="Tous": 
                    if total_entre>0 or total_sortie>0:# on affiche seulement les produit qui a des mouvements
                        _w1.table_rapport.insert("","end",values=(nom_produit,quantite,total_entre,total_sortie,stock_finale,commentaire))
                elif prod.find('catégorie').text==categorie_produit:
                    if total_entre>0 or total_sortie>0:# on affiche seulement les produit qui a des mouvements
                        _w1.table_rapport.insert("","end",values=(nom_produit,quantite,total_entre,total_sortie,stock_finale,commentaire))
                #on teste si le tableaux est vide
            if getTableauItems(_w1.table_rapport)==[]:
                 Messagebox.show_info(title="Information",message="Aucun mouvement du stock: d'ou pas de rapport a génerer!")
            #on changer les variables
            option_rapport=option
            date_target=mois_specique+" "+moiETanne
        case "annee_specifique":
            entre_xpath=f"mouvement[@type='Entre' and  starts-with(@date,'{anne_specique}')]/text()"
            sortie_xpath=f"mouvement[@type='Sortie' and  starts-with(@date,'{anne_specique}')]/text()"
            for prod in produits:
                nom_produit=prod.find('nom').text
                quantite=int(prod.find('quantite').text)
                entres=prod.xpath(entre_xpath)
                sorties=prod.xpath(sortie_xpath)
                total_entre=sum(liste_to_int(entres))
                total_sortie=sum(liste_to_int(sorties))
                stock_finale=(quantite+total_entre)-total_sortie
                if stock_finale==0:
                    commentaire="Stock épuisse"
                elif stock_finale<=25:
                    commentaire="Stock critique"
                elif stock_finale>25 and stock_finale<=250:
                    commentaire="Stock bon"
                elif stock_finale>250:
                     commentaire="Sur stock"
                #on test si l'utilisateur a choisier un catégorie specifique
                if categorie_produit=="Tous": 
                    if total_entre>0 or total_sortie>0:# on affiche seulement les produit qui a des mouvements
                        _w1.table_rapport.insert("","end",values=(nom_produit,quantite,total_entre,total_sortie,stock_finale,commentaire))
                elif prod.find('catégorie').text==categorie_produit:
                    if total_entre>0 or total_sortie>0:# on affiche seulement les produit qui a des mouvements
                        _w1.table_rapport.insert("","end",values=(nom_produit,quantite,total_entre,total_sortie,stock_finale,commentaire))
                #on teste si le tableaux est vide
            if getTableauItems(_w1.table_rapport)==[]:
                 Messagebox.show_info(title="Information",message="Aucun mouvement du stock: d'ou pas de rapport a génerer!")
            #on changer les variables
            option_rapport=option
            date_target=anne_specique
        case "trim_specifique":
             #m1,m2,m3 ce sont les moi respectif de chaque trimestre
            m1,m2,m3,trimestre=trimestre_correspondant(trimestre_specifique,anne_specique)#on recuperer la trimestre correspodante
            #les total entre de chque mois
            tot_entre_m1=0
            tot_entre_m2=0
            tot_entre_m3=0
            #les total sortie de chque mois
            tot_sortie_m1=0
            tot_sortie_m2=0
            tot_sortie_m3=0
            #le somme des total
            total_entre=0
            total_sortie=0
            for prod in produits:
                nom_produit=prod.find('nom').text
                quantite=int(prod.find('quantite').text)
                #on execute les requette entre
                entre_m1=prod.xpath(f"mouvement[@type='Entre' and starts-with(@date,'{m1}')]/text()")
                entre_m2=prod.xpath(f"mouvement[@type='Entre' and starts-with(@date,'{m2}')]/text()")
                entre_m3=prod.xpath(f"mouvement[@type='Entre' and starts-with(@date,'{m3}')]/text()")
                #on execute les requette sortie
                sortie_m1=prod.xpath(f"mouvement[@type='Sortie' and  starts-with(@date,'{m1}')]/text()")
                sortie_m2=prod.xpath(f"mouvement[@type='Sortie' and  starts-with(@date,'{m2}')]/text()")
                sortie_m3=prod.xpath(f"mouvement[@type='Sortie' and  starts-with(@date,'{m3}')]/text()")
                #on calcule les entres et sorites
                #les total entre de chque mois
                tot_entre_m1=sum(liste_to_int(entre_m1))
                tot_entre_m2=sum(liste_to_int(entre_m2))
                tot_entre_m3=sum(liste_to_int(entre_m3))
                #les total sortie de chque mois
                tot_sortie_m1=sum(liste_to_int(sortie_m1))
                tot_sortie_m2=sum(liste_to_int(sortie_m2))
                tot_sortie_m3=sum(liste_to_int(sortie_m3))
                #on calcule la somme des entre
                total_entre=sum([tot_entre_m1,tot_entre_m2,tot_entre_m3])
                total_sortie=sum([tot_sortie_m1,tot_sortie_m2,tot_sortie_m3])
                stock_finale=(quantite+total_entre)-total_sortie
                if stock_finale==0:
                    commentaire="Stock épuisse"
                elif stock_finale<=25:
                    commentaire="Stock critique"
                elif stock_finale>25 and stock_finale<=250:
                    commentaire="Stock bon"
                elif stock_finale>250:
                     commentaire="Sur stock"
                #on test si l'utilisateur a choisier un catégorie specifique
                if categorie_produit=="Tous": 
                    if total_entre>0 or total_sortie>0:# on affiche seulement les produit qui a des mouvements
                        _w1.table_rapport.insert("","end",values=(nom_produit,quantite,total_entre,total_sortie,stock_finale,commentaire))
                elif prod.find('catégorie').text==categorie_produit:
                    if total_entre>0 or total_sortie>0:# on affiche seulement les produit qui a des mouvements
                        _w1.table_rapport.insert("","end",values=(nom_produit,quantite,total_entre,total_sortie,stock_finale,commentaire))
            #on teste si le tableaux est vide
            if getTableauItems(_w1.table_rapport)==[]:
               Messagebox.show_info(title="Information",message="Aucun mouvement du stock: d'ou pas de rapport a génerer!")
            option_rapport=option
            date_target=trimestre
        case "semestre_specifique":
            #m1,m2,m3,m4,m5,m6 ce sont les moi respectif de chaque semestre 
            m1,m2,m3,m4,m5,m6,semestre=semestre_correspondant(semestre_specifique,anne_specique)#on recuperer la semestre correspodante
            #les total entre de chaque mois
            tot_entre_m1=0
            tot_entre_m2=0
            tot_entre_m3=0
            tot_entre_m4=0
            tot_entre_m5=0
            tot_entre_m6=0
            #les total sortie de chaque mois
            tot_sortie_m1=0
            tot_sortie_m2=0
            tot_sortie_m3=0
            tot_sortie_m4=0
            tot_sortie_m5=0
            tot_sortie_m6=0
            #le somme des total
            total_entre=0
            total_sortie=0
            for prod in produits:
                nom_produit=prod.find('nom').text
                quantite=int(prod.find('quantite').text)
                #on execute les requette entre
                entre_m1=prod.xpath(f"mouvement[@type='Entre' and starts-with(@date,'{m1}')]/text()")
                entre_m2=prod.xpath(f"mouvement[@type='Entre' and starts-with(@date,'{m2}')]/text()")
                entre_m3=prod.xpath(f"mouvement[@type='Entre' and starts-with(@date,'{m3}')]/text()")
                entre_m4=prod.xpath(f"mouvement[@type='Entre' and starts-with(@date,'{m4}')]/text()")
                entre_m5=prod.xpath(f"mouvement[@type='Entre' and starts-with(@date,'{m5}')]/text()")
                entre_m6=prod.xpath(f"mouvement[@type='Entre' and starts-with(@date,'{m6}')]/text()")
                #on execute les requette sortie
                sortie_m1=prod.xpath(f"mouvement[@type='Sortie' and  starts-with(@date,'{m1}')]/text()")
                sortie_m2=prod.xpath(f"mouvement[@type='Sortie' and  starts-with(@date,'{m2}')]/text()")
                sortie_m3=prod.xpath(f"mouvement[@type='Sortie' and  starts-with(@date,'{m3}')]/text()")
                sortie_m4=prod.xpath(f"mouvement[@type='Sortie' and  starts-with(@date,'{m4}')]/text()")
                sortie_m5=prod.xpath(f"mouvement[@type='Sortie' and  starts-with(@date,'{m5}')]/text()")
                sortie_m6=prod.xpath(f"mouvement[@type='Sortie' and  starts-with(@date,'{m6}')]/text()")
                #on calcule les entres et sorites
                #les total entre de chaque mois
                tot_entre_m1=sum(liste_to_int(entre_m1))
                tot_entre_m2=sum(liste_to_int(entre_m2))
                tot_entre_m3=sum(liste_to_int(entre_m3))
                tot_entre_m4=sum(liste_to_int(entre_m4))
                tot_entre_m5=sum(liste_to_int(entre_m5))
                tot_entre_m6=sum(liste_to_int(entre_m6))
                #les total sortie de chaque mois
                tot_sortie_m1=sum(liste_to_int(sortie_m1))
                tot_sortie_m2=sum(liste_to_int(sortie_m2))
                tot_sortie_m3=sum(liste_to_int(sortie_m3))
                tot_sortie_m4=sum(liste_to_int(sortie_m4))
                tot_sortie_m5=sum(liste_to_int(sortie_m5))
                tot_sortie_m6=sum(liste_to_int(sortie_m6))
                #on calcule la somme des entres et sorties
                total_entre=sum([tot_entre_m1,tot_entre_m2,tot_entre_m3,tot_entre_m4,tot_entre_m5,tot_entre_m6])
                total_sortie=sum([tot_sortie_m1,tot_sortie_m2,tot_sortie_m3,tot_sortie_m4,tot_sortie_m5,tot_sortie_m6])
                stock_finale=(quantite+total_entre)-total_sortie
                if stock_finale==0:
                    commentaire="Stock épuisse"
                elif stock_finale<=25:
                    commentaire="Stock critique"
                elif stock_finale>25 and stock_finale<=250:
                    commentaire="Stock bon"
                elif stock_finale>250:
                     commentaire="Sur stock"
                #on test si l'utilisateur a choisier un catégorie specifique
                if categorie_produit=="Tous": 
                    if total_entre>0 or total_sortie>0:# on affiche seulement les produit qui a des mouvements
                        _w1.table_rapport.insert("","end",values=(nom_produit,quantite,total_entre,total_sortie,stock_finale,commentaire))
                elif prod.find('catégorie').text==categorie_produit:
                    if total_entre>0 or total_sortie>0:# on affiche seulement les produit qui a des mouvements
                        _w1.table_rapport.insert("","end",values=(nom_produit,quantite,total_entre,total_sortie,stock_finale,commentaire))
            #on teste si le tableaux est vide
            if getTableauItems(_w1.table_rapport)==[]:
               Messagebox.show_info(title="Information",message="Aucun mouvement du stock: d'ou pas de rapport a génerer!")
            option_rapport=option
            date_target=semestre


#methoder pour avoire les elements d'un tableaux
def getTableauItems(tab_target):
    data_=[]
    for items in tab_target.get_children():
        data_=tab_target.item(items,"value")
    return data_


def mois_lettreTO_chiffre(mois):#pour convertir un moi en lettre en chiffre
    dico_mois={
        "Janvier":"01",
        "Février":"02",
         "Mars":"03",
        "Avril":"04",
         "Mai":"05",
        "Juin":"06",
        "Juillet":"07",
        "Août":"08",
         "Septembre":"09",
         "Octobre":"10",
         "Novembre":"11",
        "Décembre":"12"
    }
    return dico_mois[mois]

        

def trimestre_correspondant(T,annee):#pour avoir les date correspondate a chaque trimestre
    #retourer 3 mois et le trimestre correspondate 
    match T:
        case "T1":
            return annee+"-01",annee+"-02",annee+"-03","Trimestre 1 de l'année "+annee
        case "T2":
            return annee+"-04",annee+"-05",annee+"-06","Trimestre 1 de l'année "+annee
        case "T3":
            return annee+"-07",annee+"-08",annee+"-09","Trimestre 1 de l'année "+annee
        case "T4":
            return annee+"-10",annee+"-11",annee+"-12","Trimestre 1 de l'année "+annee


def semestre_correspondant(S,annee):#pour avoir les date correspondate a chaque semestre:
    #retourner 6 mois et le semestre correspondate 
    match S:
        case "S1":
            return annee+"-01",annee+"-02",annee+"-03",annee+"-04",annee+"-05",annee+"-06","Semestre 1 de l'annee "+annee
        case "S2":
            return annee+"-07",annee+"-08",annee+"-09",annee+"-10",annee+"-11",annee+"-12","Semestre 1 de l'annee "+annee


def get_option_rapport():#methode pour avoire les option choisie entre aujourd'hui ou jour specique
    return _w1.choix_rapport.get()


def format_date(date_target,format):#methode pour avoir la date de format jour/mois/annee = 29/09/2025
    date = date_target.strftime(format)
    return date


#pour exportation d'un produit
def exportation(type_=None,categorie=None,table_target=None):
    Messagebox.ok(title="Aider",message="Lors du choix de fichier il faut ajouter son extension si pdf: rapport.pdf si json : rapport.json  si csv: rapport.csv")
    fichier=filedialog.asksaveasfilename(
        title="Choisir un fichier",
        filetypes=[("pdf","*.pdf"),("json","*.json"),("csv","*.csv")]
    )
    if fichier:
        match type_:
            case'rapport':
                data=[["Produit","Stock Initial","Entre","Sortie","Stock Final","Commentaire"]]#titre du tableaux
            case'produit':
                data=[["Produit","Catégorie","Quantite","Prix","Fournisseur","Date(annee-mois-jour)"]]#titre du tableaux
            case'fournisseur':
                data=[["Nom","Adresse","Télèphone","Email","Date"]]#titre du tableaux
        for items in table_target.get_children():
            valeur=table_target.item(items,"value")
            data.append(valeur)
        if fichier.endswith('.pdf'):
            document=SimpleDocTemplate(fichier,pagesize=A4)#creation d'un document pdf
            stylespdf=getSampleStyleSheet()# on recuperer les style qu'on peut faire
            style=stylespdf['Normal']
            # Contenu du PDF
            elements = []
            table_rapport=Table(data)
            # Style du tableau
            table_rapport.setStyle(TableStyle([
                # --- Bordures extérieures et intérieures ---
                ('GRID', (0,0), (-1,-1), 1, colors.black),
                ('BOX', (0,0), (-1,-1), 2, colors.black),

                # --- En-tête ---
                ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#0d6efd")),  # Couleur "primary" Bootstrap
                ('TEXTCOLOR', (0,0), (-1,0), colors.white),
                ('ALIGN', (0,0), (-1,0), 'CENTER'),

                # --- Corps du tableau ---
                ('ALIGN', (0,1), (-1,-1), 'CENTER'),
                ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
                ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),

                # --- Couleur alternée pour les lignes ---
                ('BACKGROUND', (0,1), (-1,-1), colors.whitesmoke),
                ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.whitesmoke, colors.lightgrey]),

                # --- Espacement ---
                ('TOPPADDING', (0,0), (-1,-1), 6),
                ('BOTTOMPADDING', (0,0), (-1,-1), 6),
            ]))

            if type_=="produit":
                #on teste l'option
                match categorie:
                    case "Tous":
                        titre=Paragraph("Tous les produits:",style)
                    case "Électronique":
                        titre=Paragraph("Tous les produits de catégorie életronique",style)
                    case "Fourniture":
                        titre=Paragraph("Tous les produits de catégorie fourniture",style)
                    case "PPN":
                        titre=Paragraph("Tous les produits de catégorie PPN",style)
                    case "Textille":
                        titre=Paragraph("Tous les produits de catégorie textille",style)
                    case "Accésoire":
                        titre=Paragraph("Tous les produits de catégorie accésoire",style)
                    case "Boisson":
                        titre=Paragraph("Tous les produits de catégorie boisson",style)
                    case None:
                        titre=Paragraph("",style)
            elif type_=="fournisseur":
                 titre=Paragraph("Tous les founisseurs:",style)
            elif type_=="rapport":
                 #on teste l'option
                match option_rapport:
                    case "jour_now":
                        titre=Paragraph(f"Rapport: du {date_target}, Catégorie produit: {_w1.Combobox_categorie_filtre_rapport.get()}",style)
                    case "jour_specifique":
                        titre=Paragraph(f"Rapport: du {date_target}, Catégorie produit: {_w1.Combobox_categorie_filtre_rapport.get()}",style)
                    case "mois_specifique":
                        titre=Paragraph(f"Rapport: du {date_target}, Catégorie produit: {_w1.Combobox_categorie_filtre_rapport.get()}",style)
                    case "annee_specifique":
                        titre=Paragraph(f"Rapport: de l'annee {date_target}, Catégorie produit: {_w1.Combobox_categorie_filtre_rapport.get()}",style)
                    case "trim_specifique":
                        titre=Paragraph(f"Rapport:  {date_target}, Catégorie produit: {_w1.Combobox_categorie_filtre_rapport.get()}",style)
                    case "semestre_specifique":
                        titre=Paragraph(f"Rapport:  {date_target}, Catégorie produit: {_w1.Combobox_categorie_filtre_rapport.get()}",style)
            espace=Spacer(height=10,width=10)
            elements.append(titre)
            elements.append(espace)
            elements.append(table_rapport)
            document.build(elements)
            Messagebox.show_info(title="Information",message=f"Le fichier: '{fichier}'  à étè exporte avec succée !")
        elif fichier.endswith('.json'):
            with open(fichier,'w',encoding="utf-8") as f:
                json.dump(data,f,indent=4)
                Messagebox.show_info(title="Information",message=f"Le fichier: '{fichier}'  à étè exporte avec succée !")
        elif fichier.endswith('.csv'):
            with open(fichier,'w',newline="",encoding="utf-8") as f:
                ecrire=csv.writer(f)
                ecrire.writerows(data)
                Messagebox.show_info(title="Information",message=f"Le fichier: '{fichier}'  à étè exporte avec succée !")


def set_image_icone(source):#methode pour avoire une icone commme image
    img=Image.open(source).resize((24,24))
    icone=ImageTk.PhotoImage(img)
    return icone


def find_produit_by_name(texte):#recherhcer un produit par son nom
    for prod in produits:
        #produit
        nom=prod.find('nom').text
        categorie=prod.find('catégorie').text
        quantite=prod.find('quantite').text
        prix=prod.find('prix').text
        nom_f=prod.find('fournisseur').text
        sorties=prod.xpath("mouvement[@type='Sortie']/text()")#on recuperer chaque sortie
        entres=prod.xpath(f"mouvement[@type='Entre']/text()")#on recuparer chaque entre
        stock_actuelle=(int(quantite)+sum(liste_to_int(entres)))-sum(liste_to_int(sorties))#on calcule lestock actuelle
        date_ajoute=prod.find('date_ajoute').text
        if texte in nom:
           return [nom,categorie,stock_actuelle,prix,nom_f,date_ajoute]
        

def display_produit_find(event,texte):#fonction pour afficher les produits chercher
        #on vide les tableau correspondant
        clear_treeview(_w1.table_inventaire_home)
        clear_treeview(_w1.table_inventaire)
        clear_treeview(_w1.table_inventaire_modifier)
        #on recuper les produit
        liste=find_produit_by_name(texte)
        _w1.table_inventaire_home.insert("","end",values=liste)
        _w1.table_inventaire.insert("","end",values=liste)
        _w1.table_inventaire_modifier.insert("","end",values=liste)


def actualiser_produit(event,entry,tab_produit1,tab_produit2,tab_produit3):#pour actualiser le produit apres chaque recherhe
    #on vide le champ de saier
    entry.delete(0,"end")
    #on reafficher les produits
    ajouter_produit_tableux_inventaire(tab_produit1)
    ajouter_produit_tableux_inventaire(tab_produit2)
    ajouter_produit_tableux_inventaire(tab_produit3)
    


def find_fournisseur_by_name(texte):#recherhcer un produit par son nom
        for f in fourniseurs:
            nom=f.find('nom_fournisseur').text
            adresse=f.find('adresse').text
            tel=f.find('télèphone').text
            email=f.find('email').text
            date=f.find('date').text
            if texte in nom:
                return [nom,adresse,tel,email,date]
            

def display_fournisseur_find(event,texte):#fonction pour afficher les produits chercher
    #on vide les tableau correspondant
    clear_treeview(_w1.table_fournisseur)
    clear_treeview(_w1.table_fournisseur_home)
    #on recuper les produit
    liste=find_fournisseur_by_name(texte)
    _w1.table_fournisseur_home.insert("","end",values=liste)
    _w1.table_fournisseur.insert("","end",values=liste)


def actualiser_fournisseur(event,entry,tab1,tab2):#pour actualiser le produit apres chaque recherhe
    #on vide le champ de saier
    entry.delete(0,"end")
    #on reafficher les produits
    ajouter_fournisseur_tableux_fournisseur(tab1)
    ajouter_fournisseur_tableux_fournisseur(tab2)


def total_entre_sortie_today():#pour avoir la total des entre et sortie des produits
    total_e=0
    total_s=0
    for prod in produits:
        sorties=prod.xpath(f"mouvement[@type='Sortie' and @date='{get_date_now()}']/text()")#on recuperer chaque sortie
        entres=prod.xpath(f"mouvement[@type='Entre'and  @date='{get_date_now()}']/text()")#on recuparer chaque entre
        total_e+=sum(liste_to_int(entres))
        total_s+=sum(liste_to_int(sorties))
    return total_e,total_s