#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.1
#  in conjunction with Tcl version 8.6
#    Oct 06, 2025 02:32:14 PM %z  platform: Windows NT

import sys
import ttkbootstrap as tk
from ttkbootstrap.constants import *
import os.path

_location = os.path.dirname(__file__)

import gui_support

_bgcolor = '#d9d9d9'
_fgcolor = '#000000'
_tabfg1 = 'black' 
_tabfg2 = 'white' 
_bgmode = 'light' 
_tabbg1 = '#d9d9d9' 
_tabbg2 = 'gray40' 

class Toplevel1:
    def __init__(self, top=None):
        top.geometry("1280x720+80+29")
        top.minsize(120, 1)
        top.maxsize(1540, 845)
        top.resizable(1,  1)
        top.title("Toplevel 0")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="#000000")

        self.top = top

        self.Frame_home = tk.Frame(self.top)
        self.Frame_home.place(relx=0.117, rely=0.083, relheight=0.896
                , relwidth=0.871)

        self.Frame_graphe_pie = tk.Frame(self.Frame_home)
        self.Frame_graphe_pie.place(relx=0.565, rely=0.341, relheight=0.628
                , relwidth=0.417)

        self.Frame_grpahe_courbe = tk.Frame(self.Frame_home)
        self.Frame_grpahe_courbe.place(relx=0.018, rely=0.341, relheight=0.628
                , relwidth=0.526)

        self.Frame_total_budget = tk.Frame(self.Frame_home,bootstyle="info")
        self.Frame_total_budget.place(relx=0.018, rely=0.062, relheight=0.225
                , relwidth=0.309)

        self.Label_totalBudget = tk.Label(self.Frame_total_budget)
        self.Label_totalBudget.place(relx=0.35, rely=0.069, height=21
                , width=104)
        self.Label_totalBudget.configure(text='''Total budget :''')

        self.Frame_mouvement = tk.Frame(self.Frame_home,bootstyle="info")
        self.Frame_mouvement.place(relx=0.673, rely=0.062, relheight=0.225
                , relwidth=0.283)

        self.Label_mouvement = tk.Label(self.Frame_mouvement)
        self.Label_mouvement.place(relx=0.290, rely=0.069, height=21, width=150)
        self.Label_mouvement.configure(text='''Mouvement du stock :''')

        self.Frame_stock_critique = tk.Frame(self.Frame_home,bootstyle="info")
        self.Frame_stock_critique.place(relx=0.359, rely=0.062, relheight=0.225
                , relwidth=0.283)

        self.Label_stockCritique = tk.Label(self.Frame_stock_critique)
        self.Label_stockCritique.place(relx=0.25, rely=0.062, height=21
                , width=187)
        self.Label_stockCritique.configure(text='''Niveaux de stock critique :''')

        self.Frame_menu_bare = tk.Frame(self.top)
        self.Frame_menu_bare.place(relx=0.0, rely=0.0, relheight=0.069
                , relwidth=1.004)

        self.Frame_menu_principale = tk.Frame(self.top)
        self.Frame_menu_principale.place(relx=0.007, rely=0.088, relheight=0.897
                , relwidth=0.093)
        #on cree notre menu tree
        self.menu=tk.Treeview(self.Frame_menu_principale)
        self.menu.pack(fill="both",expand=True)
        #on creer nos menus et sous-menu
        #menu inventaire
        menu_inventaire=self.menu.insert("","end",text="Inventaire",open=True)
        #ses sous menu
        self.menu.insert(menu_inventaire,'end',text="Ajouter")
        self.menu.insert(menu_inventaire,'end',text="Modifier")
        self.menu.insert(menu_inventaire,'end',text="Suprimer")
        #menu fournisseur
        menu_fournisseur=self.menu.insert("","end",text="Fournisseur",open=True)
        #ses sous menu
        self.menu.insert(menu_fournisseur,"end",text="Ajouter")
        self.menu.insert(menu_fournisseur,"end",text="Modifier")
        self.menu.insert(menu_fournisseur,"end",text="Suprimer")
        #menu Rapport
        menu_rapport=self.menu.insert("","end",text="Rapport",open=True)
        #ses sous menu
        self.menu.insert(menu_rapport,"end",text="Journalier")
        self.menu.insert(menu_rapport,"end",text="Hebdomadaire")
        self.menu.insert(menu_rapport,"end",text="Mensuel")
        self.menu.insert(menu_rapport,"end",text="Annuelle")

        self.TSeparator1 = tk.Separator(self.Frame_menu_principale)
        self.TSeparator1.place(relx=-0.104, rely=0.803,  relwidth=1.16)

        self.Button_quitter = tk.Button(self.Frame_menu_principale,bootstyle="danger")
        self.Button_quitter.place(relx=0.08, rely=0.896, height=36, width=107)
        self.Button_quitter.configure(text='''Quitter''')

def start_up():
    gui_support.main()

if __name__ == '__main__':
    gui_support.main()




